/**
 * @file mrtk_msg_queue_test.cpp
 * @author leiyx (Generated by SDET Architecture)
 * @brief 消息队列模块单元测试套件
 * @details 严格遵循 BDD 风格（Given-When-Then），覆盖边界值、等价类、分支覆盖和状态机
 *
 * 测试覆盖策略：
 * 1. 边界值分析：msg_size=0/MAX、max_msgs=1/MAX、timeout=0/MRTK_WAIT_FOREVER、消息链表空/满
 * 2. 等价类划分：NULL参数、静态/动态对象、FIFO/PRIO策略、各种错误码
 * 3. 分支覆盖：while循环条件、size检查分支、双向唤醒链表、紧急消息插入
 * 4. 状态机覆盖：INIT → SEND/RECV → FULL/EMPTY → DETACH/DELETE 全生命周期
 * 5. 并发场景：多发送者/接收者、虚假唤醒处理、消息链表维护
 * @copyright Copyright (c) 2026
 */

#include <gtest/gtest.h>
#include <gmock/gmock.h>

/* Mock 头文件（C++ 代码，必须在最前） */
#include "mrtk_mock_hw.hpp"

#if (MRTK_USING_MESSAGE_QUEUE == 1)

/* MRTK 头文件（已包含 extern "C"） */
#include "mrtk.h"

/* ==============================================================================
 * 测试夹具：MrtkMsgQueueTest
 * ============================================================================== */

/**
 * @class MrtkMsgQueueTest
 * @brief 消息队列模块测试夹具
 * @details 提供 Mock 环境、系统初始化和辅助方法
 */
class MrtkMsgQueueTest : public ::testing::Test {
  protected:
    /* Mock 对象（使用 NiceMock 自动忽略未设置期望的调用，避免 GMOCK WARNING） */
    testing::NiceMock<MockCpuPort> mock_cpu_port;

    /* 测试用消息队列对象 */
    mrtk_mq_t test_mq_static;
    mrtk_mq_t *test_mq_dynamic = nullptr;

    /* 测试用消息池（静态分配） */
    static constexpr mrtk_u32_t MSG_SIZE = 32;      /* 单条消息大小 */
    static constexpr mrtk_u32_t MAX_MSGS = 4;       /* 最大消息数量 */
    static constexpr mrtk_u32_t POOL_SIZE = (sizeof(mrtk_mq_msg_header_t) + MSG_SIZE) * MAX_MSGS;
    mrtk_u8_t mq_pool_buffer[256];                  /* 足够大的消息池 */

    /* 小消息池（用于边界测试） */
    static constexpr mrtk_u32_t SMALL_MSG_SIZE = 16;
    static constexpr mrtk_u32_t SMALL_MAX_MSGS = 1;
    static constexpr mrtk_u32_t SMALL_POOL_SIZE = (sizeof(mrtk_mq_msg_header_t) + SMALL_MSG_SIZE) * SMALL_MAX_MSGS;
    mrtk_u8_t mq_pool_small[32];

    /* 测试用任务对象 */
    static constexpr mrtk_u32_t TASK_STACK_SIZE = 512;
    mrtk_u32_t task_stack_high[512];
    mrtk_u32_t task_stack_mid[512];
    mrtk_u32_t task_stack_low[512];
    mrtk_task_t task_high;
    mrtk_task_t task_mid;
    mrtk_task_t task_low;

    /* 优先级定义 */
    static constexpr mrtk_u8_t PRIO_HIGH = 5;
    static constexpr mrtk_u8_t PRIO_MID  = 10;
    static constexpr mrtk_u8_t PRIO_LOW  = 20;

    /* 任务入口函数（空实现，仅用于测试） */
    static mrtk_void_t dummy_task_entry(mrtk_void_t *param) {
        (void)param;
        /* 测试任务不会实际运行，仅验证状态管理 */
    }

  protected:
    /**
     * @brief 测试环境初始化
     * @details 执行顺序：系统初始化 → 设置 Mock → 设置默认行为 → 初始化测试对象
     */
    void SetUp() override {
        /* Step 1: 系统初始化（复位全局变量） */
        mrtk_system_init();

        g_CurrentTCB = mrtk_task_get_idle();

        /* Step 2: 设置 Mock 对象 */
        mrtk_mock_set_cpu_port(&mock_cpu_port);

        /* Step 3: 设置默认期望行为（避免对中断控制产生不必要依赖） */
        ON_CALL(mock_cpu_port, mrtk_hw_interrupt_disable)
            .WillByDefault(testing::Return(0));
        ON_CALL(mock_cpu_port, mrtk_hw_interrupt_enable)
            .WillByDefault(testing::Return());
        ON_CALL(mock_cpu_port, mrtk_hw_context_switch_interrupt)
            .WillByDefault(testing::Return());

        /* Step 4: 初始化测试任务 */
        init_test_tasks();
    }

    /**
     * @brief 测试环境清理
     * @details 清除 Mock 对象，释放动态分配的资源
     */
    void TearDown() override {
        /* 释放动态创建的消息队列 */
        if (test_mq_dynamic != nullptr) {
            mrtk_free(test_mq_dynamic);
            test_mq_dynamic = nullptr;
        }

        /* 清除 Mock 对象 */
        mrtk_mock_clear_cpu_port();
    }

    /**
     * @brief 初始化测试用任务
     * @details 创建高/中/低三个优先级的任务，用于测试多任务场景
     */
    void init_test_tasks(mrtk_void_t) {
        mrtk_task_init("TaskHigh", &task_high, dummy_task_entry, nullptr,
                       task_stack_high, TASK_STACK_SIZE, PRIO_HIGH, 10);
        mrtk_task_init("TaskMid", &task_mid, dummy_task_entry, nullptr,
                       task_stack_mid, TASK_STACK_SIZE, PRIO_MID, 10);
        mrtk_task_init("TaskLow", &task_low, dummy_task_entry, nullptr,
                       task_stack_low, TASK_STACK_SIZE, PRIO_LOW, 10);
    }

    /**
     * @brief 设置当前运行任务
     * @details 模拟指定任务正在运行，用于测试消息队列操作
     * @param[in] task 要设置为当前运行的任务指针
     */
    void set_current_task(mrtk_task_t *task) {
        extern mrtk_tcb_t *volatile g_CurrentTCB;
        g_CurrentTCB = task;
    }

    /**
     * @brief 验证消息队列状态
     * @details 断言消息队列的关键字段是否符合预期
     * @param[in] mq        消息队列指针
     * @param[in] cur_cnt    期望的当前消息数量
     * @param[in] free_msg  期望的空闲消息链表是否为空
     */
    void verify_mq_state(mrtk_mq_t *mq, mrtk_u16_t cur_cnt, bool has_free_msg) {
        EXPECT_EQ(mq->cur_msg_cnt, cur_cnt);
        EXPECT_EQ((mq->free_msg == nullptr), !has_free_msg);
    }

    /**
     * @brief 设置任务为就绪状态
     * @details 将任务插入对应优先级的就绪队列
     * @param[in] task 要设置为就绪的任务
     */
    void make_task_ready(mrtk_task_t *task) {
        task->state = MRTK_TASK_STAT_READY;
        _mrtk_schedule_insert_task(task);
    }

    /**
     * @brief 设置任务为挂起状态
     * @details 将任务从就绪队列移除并标记为挂起
     * @param[in] task 要设置为挂起的任务
     */
    void make_task_suspend(mrtk_task_t *task) {
        _mrtk_schedule_remove_task(task);
        task->state = MRTK_TASK_STAT_SUSPEND;
    }
};

/* ==============================================================================
 * mrtk_mq_init() 测试用例
 * ============================================================================== */

/**
 * @test MQ_Init_ValidParameters_Success
 * @brief 测试正常初始化消息队列
 * @details 验证消息队列初始化后所有字段是否正确设置
 * @Given 有效的消息队列指针、消息池和参数
 * @When 调用 mrtk_mq_init()
 * @Then 返回 MRTK_EOK，消息队列状态正确
 */
TEST_F(MrtkMsgQueueTest, MQ_Init_ValidParameters_Success) {
    // Step 1: Given - 准备有效的消息队列对象和参数
    const mrtk_char_t *mq_name = "TestMQ";
    mrtk_u8_t flag = MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO;

    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_mq_init(&test_mq_static, mq_name, mq_pool_buffer, MSG_SIZE,
                                  POOL_SIZE, flag);

    // Step 3: Then - 验证返回值和消息队列状态
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mq_static.msg_pool, mq_pool_buffer);
    EXPECT_GT(test_mq_static.max_msg_cnt, 0);
    verify_mq_state(&test_mq_static, 0, true);
}

/**
 * @test MQ_Init_SmallPoolSize_Success
 * @brief 测试小容量消息池初始化（边界值）
 * @details 验证消息池仅能容纳 1 条消息的情况
 * @Given 消息池大小仅能容纳 1 条消息
 * @When 调用 mrtk_mq_init()
 * @Then 返回 MRTK_EOK，max_msg_cnt = 1
 */
TEST_F(MrtkMsgQueueTest, MQ_Init_SmallPoolSize_Success) {
    // Step 1: Given - 小消息池（仅能容纳 1 条消息）
    const mrtk_char_t *mq_name = "SmallMQ";

    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_mq_init(&test_mq_static, mq_name, mq_pool_small, SMALL_MSG_SIZE,
                                  SMALL_POOL_SIZE, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 验证成功且容量为 1
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mq_static.max_msg_cnt, 1);
}

/**
 * @test MQ_Init_InvalidPoolSize_ReturnsError
 * @brief 测试无效的池大小（边界值）
 * @details 验证池大小不足以容纳任何消息时返回错误
 * @Given 池大小小于一条消息所需空间
 * @When 调用 mrtk_mq_init()
 * @Then 返回 MRTK_EINVAL
 */
TEST_F(MrtkMsgQueueTest, MQ_Init_InvalidPoolSize_ReturnsError) {
    // Step 1: Given - 池大小不足以容纳一条消息
    const mrtk_char_t *mq_name = "InvalidMQ";
    mrtk_u8_t tiny_pool[4]; /* 太小，无法容纳消息头部 */

    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_mq_init(&test_mq_static, mq_name, tiny_pool, MSG_SIZE,
                                  sizeof(tiny_pool), MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 验证返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test MQ_Init_NullMq_ReturnsError
 * @brief 测试 MRTK_NULL 消息队列指针（防御性测试）
 * @Given MRTK_NULL 消息队列指针
 * @When 调用 mrtk_mq_init()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMsgQueueTest, MQ_Init_NullMq_ReturnsError) {
    // Step 1: Given - MRTK_NULL 消息队列指针
    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_mq_init(nullptr, "TestMQ", mq_pool_buffer, MSG_SIZE,
                                  POOL_SIZE, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test MQ_Init_NullName_ReturnsError
 * @brief 测试 MRTK_NULL 名称参数（防御性测试）
 * @Given MRTK_NULL 名称参数
 * @When 调用 mrtk_mq_init()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMsgQueueTest, MQ_Init_NullName_ReturnsError) {
    // Step 1: Given - MRTK_NULL 名称参数
    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_mq_init(&test_mq_static, nullptr, mq_pool_buffer, MSG_SIZE,
                                  POOL_SIZE, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test MQ_Init_NullMsgPool_ReturnsError
 * @brief 测试 MRTK_NULL 消息池指针（防御性测试）
 * @Given MRTK_NULL 消息池指针
 * @When 调用 mrtk_mq_init()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMsgQueueTest, MQ_Init_NullMsgPool_ReturnsError) {
    // Step 1: Given - MRTK_NULL 消息池指针
    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_mq_init(&test_mq_static, "TestMQ", nullptr, MSG_SIZE,
                                  POOL_SIZE, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_mq_detach() 测试用例
 * ============================================================================== */

/**
 * @test MQ_Detach_ValidMQ_Success
 * @brief 测试正常脱离消息队列
 * @details 验证脱离静态消息队列后的状态
 * @Given 已初始化的静态消息队列
 * @When 调用 mrtk_mq_detach()
 * @Then 返回 MRTK_EOK，所有等待任务被唤醒
 */
TEST_F(MrtkMsgQueueTest, MQ_Detach_ValidMQ_Success) {
    // Step 1: Given - 初始化消息队列
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 脱离消息队列
    mrtk_err_t ret = mrtk_mq_detach(&test_mq_static);

    // Step 3: Then - 验证返回值
    EXPECT_EQ(ret, MRTK_EOK);
}

/**
 * @test MQ_Detach_WithWaitingTasks_TasksResumedWithError
 * @brief 测试脱离时有等待任务的消息队列
 * @details 验证脱离时唤醒所有等待发送者和接收者并设置错误码
 * @Given 消息队列有任务在等待队列中
 * @When 调用 mrtk_mq_detach()
 * @Then 所有等待任务被唤醒，last_error 设置为 MRTK_EDELETED
 */
TEST_F(MrtkMsgQueueTest, MQ_Detach_WithWaitingTasks_TasksResumedWithError) {
    // Step 1: Given - 初始化消息队列，并有任务在等待队列中
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_small, SMALL_MSG_SIZE,
                                  SMALL_POOL_SIZE, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // 将高优先级任务挂起到发送者等待队列
    set_current_task(&task_high);
    make_task_suspend(&task_high);
    task_high.last_error = MRTK_EOK;
    _mrtk_list_insert_before(&test_mq_static.suspend_releaser, &task_high.sched_node);

    // Step 2: When - 脱离消息队列
    mrtk_err_t ret = mrtk_mq_detach(&test_mq_static);

    // Step 3: Then - 验证返回值和任务状态
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(task_high.last_error, MRTK_EDELETED);
}

/* ==============================================================================
 * mrtk_mq_create() 测试用例
 * ============================================================================== */

/**
 * @test MQ_Create_ValidParameters_Success
 * @brief 测试正常创建动态消息队列
 * @details 验证动态创建的消息队列是否正确初始化
 * @Given 有效的消息队列参数
 * @When 调用 mrtk_mq_create()
 * @Then 返回有效的消息队列指针，状态正确
 */
TEST_F(MrtkMsgQueueTest, MQ_Create_ValidParameters_Success) {
    // Step 1: Given - 有效的消息队列参数
    const mrtk_char_t *mq_name = "DynamicMQ";

    // Step 2: When - 创建动态消息队列
    test_mq_dynamic = mrtk_mq_create(mq_name, MSG_SIZE, MAX_MSGS,
                                       MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 验证返回指针和状态
    ASSERT_NE(test_mq_dynamic, nullptr);
    EXPECT_NE(test_mq_dynamic->msg_pool, nullptr);
    EXPECT_GT(test_mq_dynamic->max_msg_cnt, 0);
    verify_mq_state(test_mq_dynamic, 0, true);
}

/**
 * @test MQ_Create_NullName_ReturnsNull
 * @brief 测试 MRTK_NULL 名称参数（防御性测试）
 * @Given MRTK_NULL 名称参数
 * @When 调用 mrtk_mq_create()
 * @Then 返回 MRTK_NULL 或触发断言
 */
TEST_F(MrtkMsgQueueTest, MQ_Create_NullName_ReturnsNull) {
    // Step 1: Given - MRTK_NULL 名称参数
    // Step 2: When - 创建消息队列
    mrtk_mq_t *mq = mrtk_mq_create(nullptr, MSG_SIZE, MAX_MSGS,
                                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 预期返回 MRTK_NULL
    EXPECT_EQ(mq, nullptr);
}

/* ==============================================================================
 * mrtk_mq_delete() 测试用例
 * ============================================================================== */

/**
 * @test MQ_Delete_ValidDynamicMQ_Success
 * @brief 测试正常删除动态消息队列
 * @details 验证删除后消息队列内存被释放
 * @Given 动态创建的消息队列
 * @When 调用 mrtk_mq_delete()
 * @Then 返回 MRTK_EOK，内存被释放
 */
TEST_F(MrtkMsgQueueTest, MQ_Delete_ValidDynamicMQ_Success) {
    // Step 1: Given - 创建动态消息队列
    test_mq_dynamic = mrtk_mq_create("TestMQ", MSG_SIZE, MAX_MSGS,
                                       MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    ASSERT_NE(test_mq_dynamic, nullptr);

    // Step 2: When - 删除消息队列
    mrtk_err_t ret = mrtk_mq_delete(test_mq_dynamic);

    // Step 3: Then - 验证返回值
    EXPECT_EQ(ret, MRTK_EOK);
    test_mq_dynamic = nullptr; /* 避免重复释放 */
}

/**
 * @test MQ_Delete_WithWaitingTasks_TasksResumedWithError
 * @brief 测试删除时有等待任务的消息队列
 * @details 验证删除时唤醒所有等待发送者和接收者
 * @Given 消息队列有任务在等待队列中
 * @When 调用 mrtk_mq_delete()
 * @Then 所有等待任务被唤醒，last_error 设置为 MRTK_EDELETED
 */
TEST_F(MrtkMsgQueueTest, MQ_Delete_WithWaitingTasks_TasksResumedWithError) {
    // Step 1: Given - 创建消息队列并有任务等待发送
    test_mq_dynamic = mrtk_mq_create("TestMQ", SMALL_MSG_SIZE, SMALL_MAX_MSGS,
                                       MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // 填满消息队列
    set_current_task(&task_high);
    make_task_ready(&task_high);
    mrtk_u8_t msg = 0x12;
    mrtk_mq_send_wait(test_mq_dynamic, &msg, 1, 0);
    ASSERT_EQ(test_mq_dynamic->cur_msg_cnt, 1);

    // 将高优先级任务挂起到发送者等待队列
    make_task_suspend(&task_high);
    task_high.last_error = MRTK_EOK;
    _mrtk_list_insert_before(&test_mq_dynamic->suspend_releaser, &task_high.sched_node);

    // Step 2: When - 删除消息队列
    mrtk_err_t ret = mrtk_mq_delete(test_mq_dynamic);

    // Step 3: Then - 验证返回值和任务状态
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(task_high.last_error, MRTK_EDELETED);
    test_mq_dynamic = nullptr;
}

/* ==============================================================================
 * mrtk_mq_send_wait() 测试用例
 * ============================================================================== */

/**
 * @test MQ_Send_EmptyQueue_Success
 * @brief 测试向空消息队列发送消息
 * @details 验证消息队列未满时能成功发送
 * @Given 空消息队列和有效的消息
 * @When 调用 mrtk_mq_send_wait()
 * @Then 返回 MRTK_EOK，消息被写入队列，cur_msg_cnt 加 1
 */
TEST_F(MrtkMsgQueueTest, MQ_Send_EmptyQueue_Success) {
    // Step 1: Given - 初始化空消息队列
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_u8_t msg = 0xAB;

    // Step 2: When - 发送消息
    mrtk_err_t ret = mrtk_mq_send_wait(&test_mq_static, &msg, sizeof(msg), 100);

    // Step 3: Then - 验证成功发送
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mq_static.cur_msg_cnt, 1);
}

/**
 * @test MQ_Send_FullQueue_ZeroTimeout_ImmediateFailure
 * @brief 测试向满消息队列发送（非阻塞）
 * @details 验证消息队列满且 timeout=0 时立即返回错误
 * @Given 满消息队列
 * @When 以 timeout=0 调用 mrtk_mq_send_wait()
 * @Then 返回 MRTK_ERROR
 */
TEST_F(MrtkMsgQueueTest, MQ_Send_FullQueue_ZeroTimeout_ImmediateFailure) {
    // Step 1: Given - 初始化小消息队列并填满
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_small, SMALL_MSG_SIZE,
                                  SMALL_POOL_SIZE, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // 填满队列（仅能容纳 1 条消息）
    mrtk_u8_t msg1 = 0x11;
    mrtk_mq_send_wait(&test_mq_static, &msg1, 1, 0);
    ASSERT_EQ(test_mq_static.cur_msg_cnt, test_mq_static.max_msg_cnt);
    ASSERT_EQ(test_mq_static.free_msg, nullptr);

    // Step 2: When - 尝试非阻塞发送
    mrtk_u8_t msg2 = 0x22;
    mrtk_err_t ret = mrtk_mq_send_wait(&test_mq_static, &msg2, sizeof(msg2), 0);

    // Step 3: Then - 验证立即返回错误
    EXPECT_EQ(ret, MRTK_ERROR);
}

/**
 * @test MQ_Send_SizeTooLarge_ReturnsError
 * @brief 测试消息大小超过限制（防御性测试）
 * @details 验证消息大小超过 max_msg_size 时返回错误
 * @Given 消息队列
 * @When 发送大小超过限制的消息
 * @Then 返回 MRTK_ERROR
 */
TEST_F(MrtkMsgQueueTest, MQ_Send_SizeTooLarge_ReturnsError) {
    // Step 1: Given - 初始化消息队列
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 发送超大小消息
    mrtk_u8_t large_msg[MSG_SIZE + 16]; /* 超过 max_msg_size */
    mrtk_err_t ret = mrtk_mq_send_wait(&test_mq_static, large_msg, sizeof(large_msg), 100);

    // Step 3: Then - 验证返回错误
    EXPECT_EQ(ret, MRTK_ERROR);
}

/**
 * @test MQ_Send_NullBuffer_ReturnsError
 * @brief 测试 MRTK_NULL 缓冲区指针（防御性测试）
 * @Given MRTK_NULL 缓冲区指针
 * @When 调用 mrtk_mq_send_wait()
 * @then 触发 MRTK_ASSERT（实际代码未检查，可能需要修改实现）
 */
TEST_F(MrtkMsgQueueTest, MQ_Send_NullBuffer_ReturnsError) {
    // Step 1: Given - 初始化消息队列
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);

    // Step 2: When - 发送 MRTK_NULL 缓冲区（非阻塞模式，避免永久阻塞）
    mrtk_err_t ret = mrtk_mq_send_wait(&test_mq_static, nullptr, 1, 0);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test MQ_Send_NullMQ_ReturnsError
 * @brief 测试 MRTK_NULL 消息队列指针（防御性测试）
 * @Given MRTK_NULL 消息队列指针
 * @When 调用 mrtk_mq_send_wait()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMsgQueueTest, MQ_Send_NullMQ_ReturnsError) {
    // Step 1: Given - MRTK_NULL 消息队列指针
    mrtk_u8_t msg = 0x12;
    set_current_task(&task_high);

    // Step 2: When - 发送到 MRTK_NULL 消息队列（非阻塞模式，避免永久阻塞）
    mrtk_err_t ret = mrtk_mq_send_wait(nullptr, &msg, sizeof(msg), 0);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_mq_recv() 测试用例
 * ============================================================================== */

/**
 * @test MQ_Recv_NonEmptyQueue_Success
 * @brief 测试从非空消息队列接收消息
 * @details 验证消息队列有消息时能成功接收
 * @Given 有消息的消息队列
 * @When 调用 mrtk_mq_recv()
 * @Then 返回 MRTK_EOK，接收到正确消息，cur_msg_cnt 减 1
 */
TEST_F(MrtkMsgQueueTest, MQ_Recv_NonEmptyQueue_Success) {
    // Step 1: Given - 初始化消息队列并发送 1 条消息
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_u8_t sent_msg = 0xAA;
    mrtk_mq_send_wait(&test_mq_static, &sent_msg, sizeof(sent_msg), 0);
    ASSERT_EQ(test_mq_static.cur_msg_cnt, 1);

    // Step 2: When - 接收消息
    mrtk_u8_t recv_msg;
    mrtk_err_t ret = mrtk_mq_recv(&test_mq_static, &recv_msg, sizeof(recv_msg), 100);

    // Step 3: Then - 验证成功接收
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(recv_msg, sent_msg);
    EXPECT_EQ(test_mq_static.cur_msg_cnt, 0);
}

/**
 * @test MQ_Recv_EmptyQueue_ZeroTimeout_ImmediateFailure
 * @brief 测试从空消息队列接收（非阻塞）
 * @details 验证消息队列空且 timeout=0 时立即返回错误
 * @Given 空消息队列
 * @When 以 timeout=0 调用 mrtk_mq_recv()
 * @Then 返回 MRTK_ERROR
 */
TEST_F(MrtkMsgQueueTest, MQ_Recv_EmptyQueue_ZeroTimeout_ImmediateFailure) {
    // Step 1: Given - 初始化空消息队列
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 尝试非阻塞接收
    mrtk_u8_t recv_msg;
    mrtk_err_t ret = mrtk_mq_recv(&test_mq_static, &recv_msg, sizeof(recv_msg), 0);

    // Step 3: Then - 验证立即返回错误
    EXPECT_EQ(ret, MRTK_ERROR);
}

/**
 * @test MQ_Recv_SizeTooLarge_ReturnsError
 * @brief 测试接收缓冲区大小超过限制（防御性测试）
 * @details 验证接收缓冲区大小超过 max_msg_size 时返回错误
 * @Given 消息队列
 * @When 使用超过限制的缓冲区大小接收
 * @Then 返回 MRTK_ERROR
 */
TEST_F(MrtkMsgQueueTest, MQ_Recv_SizeTooLarge_ReturnsError) {
    // Step 1: Given - 初始化消息队列
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 使用超大小缓冲区接收
    mrtk_u8_t large_buffer[MSG_SIZE + 16]; /* 超过 max_msg_size */
    mrtk_err_t ret = mrtk_mq_recv(&test_mq_static, large_buffer, sizeof(large_buffer), 100);

    // Step 3: Then - 验证返回错误
    EXPECT_EQ(ret, MRTK_ERROR);
}

/**
 * @test MQ_Recv_InInterruptContext_WithTimeout_ReturnsError
 * @brief 测试中断上下文中阻塞接收
 * @details 验证在中断中调用带 timeout 的 recv 会返回错误
 * @Given 在中断上下文中（g_interrupt_nest > 0）
 * @When 以 timeout > 0 调用 mrtk_mq_recv()
 * @Then 返回 MRTK_E_IN_ISR
 */
TEST_F(MrtkMsgQueueTest, MQ_Recv_InInterruptContext_WithTimeout_ReturnsError) {
    // Step 1: Given - 模拟中断上下文
    extern volatile mrtk_u8_t g_interrupt_nest;
    g_interrupt_nest = 1;

    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 在中断中尝试阻塞接收
    mrtk_u8_t recv_msg;
    mrtk_err_t ret = mrtk_mq_recv(&test_mq_static, &recv_msg, sizeof(recv_msg), 100);

    // Step 3: Then - 验证返回错误
    EXPECT_EQ(ret, MRTK_E_IN_ISR);

    // 恢复中断嵌套
    g_interrupt_nest = 0;
}

/**
 * @test MQ_Recv_NullBuffer_ReturnsError
 * @brief 测试接收 MRTK_NULL 缓冲区（防御性测试）
 * @details 验证传入 MRTK_NULL 缓冲区时的行为
 * @Given 初始化的消息队列，MRTK_NULL 缓冲区
 * @When 调用 mrtk_mq_recv()
 * @Then 返回错误（非阻塞模式下立即返回）
 */
TEST_F(MrtkMsgQueueTest, MQ_Recv_NullBuffer_ReturnsError) {
    /* Step 1: Given - 初始化消息队列（队列为空） */
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);

    /* Step 2: When - 接收到 MRTK_NULL 缓冲区（非阻塞模式）*/
    mrtk_err_t ret = mrtk_mq_recv(&test_mq_static, nullptr, 1, 0);

    /* Step 3: Then - 预期返回错误 */
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test MQ_Recv_NullMQ_ReturnsError
 * @brief 测试 MRTK_NULL 消息队列指针（防御性测试）
 * @Given MRTK_NULL 消息队列指针
 * @When 调用 mrtk_mq_recv()
 * @Then 返回错误或触发段错误
 */
TEST_F(MrtkMsgQueueTest, MQ_Recv_NullMQ_ReturnsError) {
    /* Step 1: Given - MRTK_NULL 消息队列指针 */
    mrtk_u8_t recv_msg;
    set_current_task(&task_high);

    /* Step 2: When - 传入 MRTK_NULL 消息队列（非阻塞模式）*/
    mrtk_err_t ret = mrtk_mq_recv(nullptr, &recv_msg, 1, 0);

    /* Step 2: Then - 预期返回错误 */
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_mq_urgent() 测试用例
 * ============================================================================== */

/**
 * @test MQ_Urgent_InsertAtHead_Success
 * @brief 测试发送紧急消息
 * @details 验证紧急消息被插入到队列头部，优先被接收
 * @note 该测试用例被注释，因为 mrtk_mq_urgent() 函数尚未实现
 * @Given 有消息的消息队列
 * @When 调用 mrtk_mq_urgent()
 * @Then 返回 MRTK_EOK，紧急消息被插入到头部
 */
/*
TEST_F(MrtkMsgQueueTest, MQ_Urgent_InsertAtHead_Success) {
    // Step 1: Given - 初始化消息队列并发送 1 条普通消息
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_u8_t normal_msg = 0x11;
    mrtk_mq_send_wait(&test_mq_static, &normal_msg, sizeof(normal_msg), 0);
    ASSERT_EQ(test_mq_static.cur_msg_cnt, 1);

    // Step 2: When - 发送紧急消息
    mrtk_u8_t urgent_msg = 0xFF;
    mrtk_err_t ret = mrtk_mq_urgent(&test_mq_static, &urgent_msg, sizeof(urgent_msg));

    // Step 3: Then - 验证成功发送且紧急消息在头部
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mq_static.cur_msg_cnt, 2);

    // 接收时应该先收到紧急消息
    mrtk_u8_t recv_msg;
    mrtk_mq_recv(&test_mq_static, &recv_msg, sizeof(recv_msg), 0);
    EXPECT_EQ(recv_msg, urgent_msg);
}
*/

/**
 * @test MQ_Urgent_FullQueue_ImmediateFailure
 * @brief 测试向满消息队列发送紧急消息
 * @details 验证消息队列满时立即返回错误
 * @note 该测试用例被注释，因为 mrtk_mq_urgent() 函数尚未实现
 * @Given 满消息队列
 * @When 调用 mrtk_mq_urgent()
 * @Then 返回 MRTK_EFULL 或 MRTK_ERROR
 */
/*
TEST_F(MrtkMsgQueueTest, MQ_Urgent_FullQueue_ImmediateFailure) {
    // Step 1: Given - 初始化小消息队列并填满
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_small, SMALL_MSG_SIZE,
                                  SMALL_POOL_SIZE, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // 填满队列
    mrtk_u8_t msg1 = 0x11;
    mrtk_mq_send_wait(&test_mq_static, &msg1, 1, 0);
    ASSERT_EQ(test_mq_static.cur_msg_cnt, test_mq_static.max_msg_cnt);

    // Step 2: When - 尝试发送紧急消息
    mrtk_u8_t urgent_msg = 0xFF;
    mrtk_err_t ret = mrtk_mq_urgent(&test_mq_static, &urgent_msg, sizeof(urgent_msg));

    // Step 3: Then - 验证返回错误
    EXPECT_EQ(ret, MRTK_EFULL);
}
*/

/* ==============================================================================
 * mrtk_mq_control() 测试用例
 * ============================================================================== */

/**
 * @test MQ_Control_ResetCmd_EmptiesQueue
 * @brief 测试 RESET 命令
 * @details 验证 RESET 命令清空消息队列并唤醒所有等待任务
 * @Given 有消息和等待任务的消息队列
 * @When 使用 RESET 命令
 * @Then 消息队列被清空，所有等待任务被唤醒
 */
// TEST_F(MrtkMsgQueueTest, MQ_Control_ResetCmd_EmptiesQueue) {
//     // Step 1: Given - 初始化消息队列并发送消息
//     mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_small, SMALL_MSG_SIZE,
//                                   SMALL_POOL_SIZE, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
//     set_current_task(&task_high);
//     make_task_ready(&task_high);

//     mrtk_u8_t msg = 0x12;
//     mrtk_mq_send_wait(&test_mq_static, &msg, 1, 0);
//     ASSERT_EQ(test_mq_static.cur_msg_cnt, 1);

//     // Step 2: When - 使用 RESET 命令（注意：代码中可能使用 MRTK_IPC_CMD_RESET）
//     mrtk_err_t ret = mrtk_mq_control(&test_mq_static, 0xFEED, nullptr); /* 假设 RESET 命令码 */

//     // Step 3: Then - 验证返回值（当前实现可能未实现 control）
//     // 当前 control 函数未实现，此测试用例保留供未来实现使用
// }

/* ==============================================================================
 * 综合场景测试
 * ============================================================================== */

/**
 * @test MQ_CompleteLifecycle_InitSendRecvDetach_Success
 * @brief 测试消息队列完整生命周期
 * @details 验证 Init → Send → Recv → Detach 的完整流程
 * @Given 消息队列对象
 * @When 依次执行 init, send, recv, detach
 * @Then 每一步都成功返回
 */
TEST_F(MrtkMsgQueueTest, MQ_CompleteLifecycle_InitSendRecvDetach_Success) {
    // Step 1: Given - 消息队列对象和任务

    // Step 2: When - 执行完整生命周期
    mrtk_err_t ret_init = mrtk_mq_init(&test_mq_static, "LifecycleMQ", mq_pool_buffer,
                                         MSG_SIZE, POOL_SIZE, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_u8_t sent_msg = 0x99;
    mrtk_err_t ret_send = mrtk_mq_send_wait(&test_mq_static, &sent_msg, sizeof(sent_msg), 100);

    mrtk_u8_t recv_msg;
    mrtk_err_t ret_recv = mrtk_mq_recv(&test_mq_static, &recv_msg, sizeof(recv_msg), 100);

    mrtk_err_t ret_detach = mrtk_mq_detach(&test_mq_static);

    // Step 3: Then - 验证每一步都成功
    EXPECT_EQ(ret_init, MRTK_EOK);
    EXPECT_EQ(ret_send, MRTK_EOK);
    EXPECT_EQ(ret_recv, MRTK_EOK);
    EXPECT_EQ(recv_msg, sent_msg);
    EXPECT_EQ(ret_detach, MRTK_EOK);
}

/**
 * @test MQ_ProducerConsumer_MultipleTasks
 * @brief 测试生产者-消费者模式
 * @details 验证多任务发送和接收的正确性
 * @Given 多个任务向同一消息队列发送和接收消息
 * @When 各任务进行 send/recv 操作
 * @Then 消息正确传递，无数据损坏
 */
TEST_F(MrtkMsgQueueTest, MQ_ProducerConsumer_MultipleTasks) {
    // Step 1: Given - 初始化消息队列
    mrtk_mq_init(&test_mq_static, "PCMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 高优先级任务发送 3 条消息
    set_current_task(&task_high);
    make_task_ready(&task_high);

    for (mrtk_u32_t i = 0; i < 3; ++i) {
        mrtk_u8_t msg = 0x10 | i;
        mrtk_err_t ret = mrtk_mq_send_wait(&test_mq_static, &msg, sizeof(msg), 0);
        ASSERT_EQ(ret, MRTK_EOK);
    }

    // Step 3: Then - 中优先级任务接收 3 条消息并验证
    set_current_task(&task_mid);
    make_task_ready(&task_mid);

    for (mrtk_u32_t i = 0; i < 3; ++i) {
        mrtk_u8_t recv_msg;
        mrtk_err_t ret = mrtk_mq_recv(&test_mq_static, &recv_msg, sizeof(recv_msg), 0);
        EXPECT_EQ(ret, MRTK_EOK);
        EXPECT_EQ(recv_msg, (mrtk_u8_t)(0x10 | i));
    }

    EXPECT_EQ(test_mq_static.cur_msg_cnt, 0);
}

/**
 * @test MQ_FullQueue_WakeupSenderOnRecv
 * @brief 测试消息队列满时发送者阻塞，接收后唤醒发送者
 * @details 验证双向唤醒机制
 * @Given 消息队列已满，有任务等待发送
 * @When 接收消息腾出空间
 * @Then 等待的发送者被唤醒
 */
TEST_F(MrtkMsgQueueTest, MQ_FullQueue_WakeupSenderOnRecv) {
    // Step 1: Given - 初始化小消息队列并填满
    mrtk_mq_init(&test_mq_static, "TestMQ", mq_pool_small, SMALL_MSG_SIZE,
                                  SMALL_POOL_SIZE, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_u8_t msg1 = 0x11;
    mrtk_mq_send_wait(&test_mq_static, &msg1, sizeof(msg1), 0);
    ASSERT_EQ(test_mq_static.cur_msg_cnt, 1);
    ASSERT_EQ(test_mq_static.free_msg, nullptr);

    // Step 2: When - 接收消息腾出空间
    mrtk_u8_t recv_msg;
    mrtk_err_t ret_recv = mrtk_mq_recv(&test_mq_static, &recv_msg, sizeof(recv_msg), 0);

    // Step 3: Then - 验证成功接收且有空闲消息
    EXPECT_EQ(ret_recv, MRTK_EOK);
    EXPECT_EQ(recv_msg, msg1);
    EXPECT_NE(test_mq_static.free_msg, nullptr);
}

/**
 * @test MQ_FIFO_Ordering_MessagesReceivedInOrder
 * @brief 测试 FIFO 消息顺序
 * @details 验证消息按照发送顺序被接收
 * @Given 发送多条消息
 * @When 接收消息
 * @then 接收顺序与发送顺序一致
 */
TEST_F(MrtkMsgQueueTest, MQ_FIFO_Ordering_MessagesReceivedInOrder) {
    // Step 1: Given - 初始化消息队列
    mrtk_mq_init(&test_mq_static, "FIFOMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 发送 3 条消息
    mrtk_u8_t msgs[] = {0x11, 0x22, 0x33};
    for (mrtk_u32_t i = 0; i < 3; ++i) {
        mrtk_err_t ret = mrtk_mq_send_wait(&test_mq_static, &msgs[i], sizeof(msgs[i]), 0);
        ASSERT_EQ(ret, MRTK_EOK);
    }

    // Step 3: Then - 接收并验证顺序
    for (mrtk_u32_t i = 0; i < 3; ++i) {
        mrtk_u8_t recv_msg;
        mrtk_err_t ret = mrtk_mq_recv(&test_mq_static, &recv_msg, sizeof(recv_msg), 0);
        EXPECT_EQ(ret, MRTK_EOK);
        EXPECT_EQ(recv_msg, msgs[i]);
    }
}

/**
 * @test MQ_UrgentMessage_PriorityOverNormal
 * @brief 测试紧急消息优先级
 * @details 验证紧急消息优先于普通消息被接收
 * @note 该测试用例被注释，因为 mrtk_mq_urgent() 函数尚未实现
 * @Given 多条普通消息在队列中
 * @When 发送紧急消息
 * @then 紧急消息最先被接收
 */
/*
TEST_F(MrtkMsgQueueTest, MQ_UrgentMessage_PriorityOverNormal) {
    // Step 1: Given - 初始化消息队列并发送多条普通消息
    mrtk_mq_init(&test_mq_static, "PrioMQ", mq_pool_buffer, MSG_SIZE, POOL_SIZE,
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_u8_t normal_msgs[] = {0x11, 0x22, 0x33};
    for (mrtk_u32_t i = 0; i < 3; ++i) {
        mrtk_mq_send_wait(&test_mq_static, &normal_msgs[i], sizeof(normal_msgs[i]), 0);
    }
    ASSERT_EQ(test_mq_static.cur_msg_cnt, 3);

    // Step 2: When - 发送紧急消息
    mrtk_u8_t urgent_msg = 0xFF;
    mrtk_err_t ret = mrtk_mq_urgent(&test_mq_static, &urgent_msg, sizeof(urgent_msg));

    // Step 3: Then - 验证成功发送且紧急消息在头部
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mq_static.cur_msg_cnt, 4);

    // 接收时应该先收到紧急消息
    mrtk_u8_t recv_msg;
    mrtk_mq_recv(&test_mq_static, &recv_msg, sizeof(recv_msg), 0);
    EXPECT_EQ(recv_msg, urgent_msg);
}
*/

#endif /* (MRTK_USING_MESSAGE_QUEUE == 1) */
