/**
 * @file mrtk_mutex_test.cpp
 * @author leiyx (Generated by SDET Architecture)
 * @brief 互斥量模块单元测试套件
 * @details 严格遵循 BDD 风格（Given-When-Then），覆盖边界值、等价类、分支覆盖和状态机
 *
 * 测试覆盖策略：
 * 1. 边界值分析：timeout=0/MAX、priority=0/31、nest=1/MAX、中断嵌套层数
 * 2. 等价类划分：NULL参数、非法对象类型、静态/动态对象
 * 3. 分支覆盖：递归锁分支、优先级继承分支、等待队列空/满
 * 4. 状态机覆盖：INIT → LOCKED → UNLOCKED → DELETED 全生命周期
 * 5. 并发场景：优先级继承、多任务等待、中断上下文
 * @copyright Copyright (c) 2026
 */

#include <gtest/gtest.h>
#include <gmock/gmock.h>

/* Mock 头文件（C++ 代码，必须在最前） */
#include "mrtk_mock_hw.hpp"

#if (MRTK_USING_MUTEX == 1)

/* MRTK 头文件（已包含 extern "C"） */
#include "mrtk.h"

/* ==============================================================================
 * 测试夹具：MrtkMutexTest
 * ============================================================================== */

/**
 * @class MrtkMutexTest
 * @brief 互斥量模块测试夹具
 * @details 提供 Mock 环境、系统初始化和辅助方法
 */
class MrtkMutexTest : public ::testing::Test {
  protected:
    /* Mock 对象（使用 NiceMock 自动忽略未设置期望的调用，避免 GMOCK WARNING） */
    testing::NiceMock<MockCpuPort> mock_cpu_port;

    /* 测试用互斥量对象 */
    mrtk_mutex_t test_mutex_static;
    mrtk_mutex_t *test_mutex_dynamic = nullptr;

    /* 测试用任务对象（静态分配栈内存） */
    static constexpr mrtk_u32_t TASK_STACK_SIZE = 512;
    mrtk_u32_t task_stack_high[512];
    mrtk_u32_t task_stack_mid[512];
    mrtk_u32_t task_stack_low[512];
    mrtk_task_t task_high;
    mrtk_task_t task_mid;
    mrtk_task_t task_low;

    /* 优先级定义 */
    #if (MRTK_PRIO_HIGHER_IS_LOWER_VALUE == 1)
    static constexpr mrtk_u8_t PRIO_HIGH = 5;
    static constexpr mrtk_u8_t PRIO_MID  = 10;
    static constexpr mrtk_u8_t PRIO_LOW  = 20;
    #else 
    static constexpr mrtk_u8_t PRIO_HIGH = 20;
    static constexpr mrtk_u8_t PRIO_MID  = 10;
    static constexpr mrtk_u8_t PRIO_LOW  = 5;
    #endif

    /* 任务入口函数（空实现，仅用于测试） */
    static mrtk_void_t dummy_task_entry(mrtk_void_t *param) {
        (void)param;
        /* 测试任务不会实际运行，仅验证状态管理 */
    }

  protected:
    /**
     * @brief 测试环境初始化
     * @details 执行顺序：系统初始化 → 设置 Mock → 设置默认行为 → 初始化测试对象
     */
    void SetUp() override {
        /* Step 1: 系统初始化（复位全局变量） */
        mrtk_system_init();
        g_CurrentTCB = mrtk_task_get_idle();

        /* Step 2: 设置 Mock 对象 */
        mrtk_mock_set_cpu_port(&mock_cpu_port);

        /* Step 3: 设置默认期望行为（避免对中断控制产生不必要依赖） */
        ON_CALL(mock_cpu_port, mrtk_hw_interrupt_disable)
            .WillByDefault(testing::Return(0));
        ON_CALL(mock_cpu_port, mrtk_hw_interrupt_enable)
            .WillByDefault(testing::Return());
        ON_CALL(mock_cpu_port, mrtk_hw_context_switch_interrupt)
            .WillByDefault(testing::Return());

        /* Step 4: 初始化测试任务 */
        init_test_tasks();
    }

    /**
     * @brief 测试环境清理
     * @details 清除 Mock 对象，释放动态分配的资源
     */
    void TearDown() override {
        /* 释放动态创建的互斥量 */
        if (test_mutex_dynamic != nullptr) {
            mrtk_free(test_mutex_dynamic);
            test_mutex_dynamic = nullptr;
        }

        /* 清除 Mock 对象 */
        mrtk_mock_clear_cpu_port();
    }

    /**
     * @brief 初始化测试用任务
     * @details 创建高/中/低三个优先级的任务，用于测试优先级继承
     */
    void init_test_tasks(mrtk_void_t) {
        mrtk_task_init("TaskHigh", &task_high, dummy_task_entry, nullptr,
                       task_stack_high, TASK_STACK_SIZE, PRIO_HIGH, 10);
        mrtk_task_init("TaskMid", &task_mid, dummy_task_entry, nullptr,
                       task_stack_mid, TASK_STACK_SIZE, PRIO_MID, 10);
        mrtk_task_init("TaskLow", &task_low, dummy_task_entry, nullptr,
                       task_stack_low, TASK_STACK_SIZE, PRIO_LOW, 10);
    }

    /**
     * @brief 设置当前运行任务
     * @details 模拟指定任务正在运行，用于测试互斥量获取/释放
     * @param[in] task 要设置为当前运行的任务指针
     */
    void set_current_task(mrtk_task_t *task) {
        extern mrtk_tcb_t *volatile g_CurrentTCB;
        g_CurrentTCB = task;
    }

    /**
     * @brief 设置中断嵌套层数
     * @details 模拟中断嵌套，用于测试中断上下文中的互斥量操作
     * @param[in] nest 中断嵌套层数
     */
    void set_interrupt_nest(mrtk_u8_t nest) {
        extern volatile mrtk_u8_t g_interrupt_nest;
        g_interrupt_nest = nest;
    }

    /**
     * @brief 验证互斥量状态
     * @details 断言互斥量的关键字段是否符合预期
     * @param[in] mutex   互斥量指针
     * @param[in] value   期望的 value 值
     * @param[in] nest    期望的 nest 值
     * @param[in] owner   期望的持有者任务（MRTK_NULL 表示无持有者）
     * @param[in] orig_prio 期望的原始优先级
     */
    void verify_mutex_state(mrtk_mutex_t *mutex, mrtk_u16_t value, mrtk_u8_t nest,
                            mrtk_task_t *owner, mrtk_u8_t orig_prio) {
        EXPECT_EQ(mutex->value, value);
        EXPECT_EQ(mutex->nest, nest);
        EXPECT_EQ(mutex->owner_task, owner);
        EXPECT_EQ(mutex->orig_prio, orig_prio);
    }

    /**
     * @brief 验证任务优先级
     * @details 断言任务的优先级是否符合预期
     * @param[in] task    任务指针
     * @param[in] priority 期望的优先级
     */
    void verify_task_priority(mrtk_task_t *task, mrtk_u8_t priority) {
        EXPECT_EQ(task->priority, priority);
    }

    /**
     * @brief 设置任务为就绪状态
     * @details 将任务插入对应优先级的就绪队列，用于测试任务恢复
     * @param[in] task 要设置为就绪的任务
     */
    void make_task_ready(mrtk_task_t *task) {
        task->state = MRTK_TASK_STAT_READY;
        _mrtk_schedule_insert_task(task);
    }

    /**
     * @brief 设置任务为挂起状态
     * @details 将任务从就绪队列移除并标记为挂起，用于测试任务阻塞
     * @param[in] task 要设置为挂起的任务
     */
    void make_task_suspend(mrtk_task_t *task) {
        _mrtk_schedule_remove_task(task);
        task->state = MRTK_TASK_STAT_SUSPEND;
    }
};

/* ==============================================================================
 * mrtk_mutex_init() 测试用例
 * ============================================================================== */

/**
 * @test Mutex_Init_ValidParameters_Success
 * @brief 测试正常初始化互斥量
 * @details 验证互斥量初始化后所有字段是否正确设置
 * @Given 有效的互斥量指针和名称
 * @When 调用 mrtk_mutex_init()
 * @Then 返回 MRTK_EOK，互斥量状态正确
 */
TEST_F(MrtkMutexTest, Mutex_Init_ValidParameters_Success) {
    // Step 1: Given - 准备有效的互斥量对象和参数
    const mrtk_char_t *mutex_name = "TestMutex";
    mrtk_u8_t flag = MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO;

    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_mutex_init(&test_mutex_static, mutex_name, flag);

    // Step 3: Then - 验证返回值和互斥量状态
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mutex_static.value, MRTK_MUTEX_STATE_UNLOCKED);
    EXPECT_EQ(test_mutex_static.nest, 0);
    EXPECT_EQ(test_mutex_static.owner_task, nullptr);
    EXPECT_EQ(test_mutex_static.orig_prio, MRTK_INVALID_U8);
}

/**
 * @test Mutex_Init_NullMutex_ReturnsError
 * @brief 测试 MRTK_NULL 互斥量指针（防御性测试）
 * @details 验证传入 MRTK_NULL 互斥量指针时的行为
 * @Given MRTK_NULL 互斥量指针
 * @When 调用 mrtk_mutex_init()
 * @Then 返回 MRTK_EINVAL
 */
TEST_F(MrtkMutexTest, Mutex_Init_NullMutex_ReturnsError) {
    /* Step 1: Given - MRTK_NULL 互斥量指针 */
    const mrtk_char_t *mutex_name = "TestMutex";

    /* Step 2: When - 执行初始化 */
    mrtk_err_t ret = mrtk_mutex_init(nullptr, mutex_name, MRTK_IPC_FLAG_NOTIFY_POLICY_FIFO);

    /* Step 3: Then - 返回 MRTK_EINVAL */
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test Mutex_Init_NullName_ReturnsError
 * @brief 测试 MRTK_NULL 名称参数（防御性测试）
 * @details 验证传入 MRTK_NULL 名称时的行为
 * @Given MRTK_NULL 名称参数
 * @When 调用 mrtk_mutex_init()
 * @Then 返回 MRTK_EINVAL
 */
TEST_F(MrtkMutexTest, Mutex_Init_NullName_ReturnsError) {
    /* Step 1: Given - MRTK_NULL 名称参数 */
    mrtk_mutex_t mutex;

    /* Step 2: When - 执行初始化 */
    mrtk_err_t ret = mrtk_mutex_init(&mutex, nullptr, MRTK_IPC_FLAG_NOTIFY_POLICY_FIFO);

    /* Step 3: Then - 返回 MRTK_EINVAL */
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test Mutex_Init_DifferentFlagTypes_Success
 * @brief 测试不同唤醒策略标志
 * @details 验证 FIFO 和 PRIO 两种唤醒策略都能正确初始化
 * @Given 有效的互斥量对象和不同的 flag 值
 * @When 分别使用 FIFO 和 PRIO 标志初始化
 * @Then 初始化成功，flag 值正确保存
 */
TEST_F(MrtkMutexTest, Mutex_Init_DifferentFlagTypes_Success) {
    // Step 1: Given - 有效的互斥量对象
    const mrtk_char_t *mutex_name = "TestMutex";

    // Step 2: When - 分别使用 FIFO 和 PRIO 标志初始化
    mrtk_err_t ret_fifo = mrtk_mutex_init(&test_mutex_static, mutex_name,
                                           MRTK_IPC_FLAG_NOTIFY_POLICY_FIFO);
    mrtk_err_t ret_prio = mrtk_mutex_init(&test_mutex_static, mutex_name,
                                           MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 两次初始化都应成功
    EXPECT_EQ(ret_fifo, MRTK_EOK);
    EXPECT_EQ(ret_prio, MRTK_EOK);
}

/* ==============================================================================
 * mrtk_mutex_detach() 测试用例
 * ============================================================================== */

/**
 * @test Mutex_Detach_ValidMutex_Success
 * @brief 测试正常脱离互斥量
 * @details 验证脱离静态互斥量后的状态
 * @Given 已初始化的静态互斥量
 * @When 调用 mrtk_mutex_detach()
 * @Then 返回 MRTK_EOK，所有等待任务被唤醒并设置错误码
 */
TEST_F(MrtkMutexTest, Mutex_Detach_ValidMutex_Success) {
    // Step 1: Given - 初始化互斥量
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 脱离互斥量
    mrtk_err_t ret = mrtk_mutex_detach(&test_mutex_static);

    // Step 3: Then - 验证返回值
    EXPECT_EQ(ret, MRTK_EOK);
}

/**
 * @test Mutex_Detach_WithWaitingTasks_TasksResumedWithError
 * @brief 测试脱离有等待任务的互斥量
 * @details 验证脱离时唤醒所有等待任务并设置 MRTK_EDELETED 错误码
 * @Given 已初始化的互斥量，且有任务在等待队列中
 * @When 调用 mrtk_mutex_detach()
 * @Then 所有等待任务被唤醒，last_error 设置为 MRTK_EDELETED
 */
TEST_F(MrtkMutexTest, Mutex_Detach_WithWaitingTasks_TasksResumedWithError) {
    // Step 1: Given - 初始化互斥量，并让低优先级任务持有，高优先级任务等待
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // 设置低优先级任务为当前运行任务并获取互斥量
    set_current_task(&task_low);
    make_task_ready(&task_low);
    mrtk_mutex_take(&test_mutex_static, 0);

    // 将高优先级任务挂起到互斥量的等待队列
    make_task_suspend(&task_high);
    _mrtk_list_insert_before(&test_mutex_static.ipc_obj.suspend_taker, &task_high.sched_node);

    // Step 2: When - 脱离互斥量
    mrtk_err_t ret = mrtk_mutex_detach(&test_mutex_static);

    // Step 3: Then - 验证返回值和高优先级任务的状态
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(task_high.last_error, MRTK_EDELETED);
    EXPECT_EQ(task_high.state, MRTK_TASK_STAT_READY); /* 被唤醒到就绪态 */
}

/**
 * @test Mutex_Detach_WithOwner_RestoresOriginalPriority
 * @brief 测试脱离有持有者的互斥量
 * @details 验证脱离时恢复持有者的原始优先级
 * @Given 互斥量被某个任务持有，且发生过优先级继承
 * @When 调用 mrtk_mutex_detach()
 * @Then 持有者的优先级恢复到原始值
 */
TEST_F(MrtkMutexTest, Mutex_Detach_WithOwner_RestoresOriginalPriority) {
    // Step 1: Given - 低优先级任务持有互斥量，原始优先级被提升
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    set_current_task(&task_low);
    make_task_ready(&task_low);
    mrtk_mutex_take(&test_mutex_static, 0);

    // 模拟优先级继承：提升低优先级任务的优先级
    test_mutex_static.orig_prio = PRIO_LOW;
    task_low.priority = PRIO_HIGH; /* 被提升 */

    // Step 2: When - 脱离互斥量
    mrtk_err_t ret = mrtk_mutex_detach(&test_mutex_static);

    mrtk_task_dump(&task_low);
    // Step 3: Then - 验证返回值和优先级恢复
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(task_low.priority, PRIO_LOW); /* 恢复到原始优先级 */
}

/**
 * @test Mutex_Detach_Null_ReturnsError
 * @brief 测试脱离 MRTK_NULL 互斥量（防御性测试）
 * @Given MRTK_NULL 互斥量指针
 * @When 调用 mrtk_mutex_detach()
 * @Then 返回错误或触发断言
 */
TEST_F(MrtkMutexTest, Mutex_Detach_Null_ReturnsError) {
    // Step 1: Given - MRTK_NULL 互斥量指针
    // Step 2: When - 执行脱离
    mrtk_err_t ret = mrtk_mutex_detach(nullptr);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_mutex_create() 测试用例
 * ============================================================================== */

/**
 * @test Mutex_Create_ValidParameters_Success
 * @brief 测试正常创建动态互斥量
 * @details 验证动态创建的互斥量是否正确初始化
 * @Given 有效的互斥量名称
 * @When 调用 mrtk_mutex_create()
 * @Then 返回有效的互斥量指针，状态正确
 */
TEST_F(MrtkMutexTest, Mutex_Create_ValidParameters_Success) {
    // Step 1: Given - 有效的互斥量名称
    const mrtk_char_t *mutex_name = "DynamicMutex";

    // Step 2: When - 创建动态互斥量
    test_mutex_dynamic = mrtk_mutex_create(mutex_name,
                                            MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 验证返回指针和状态
    ASSERT_NE(test_mutex_dynamic, nullptr);
    EXPECT_EQ(test_mutex_dynamic->value, MRTK_MUTEX_STATE_UNLOCKED);
    EXPECT_EQ(test_mutex_dynamic->nest, 0);
    EXPECT_EQ(test_mutex_dynamic->owner_task, nullptr);
}

/**
 * @test Mutex_Create_NullName_ReturnsNull
 * @brief 测试 MRTK_NULL 名称参数（防御性测试）
 * @Given MRTK_NULL 名称参数
 * @When 调用 mrtk_mutex_create()
 * @Then 返回 MRTK_NULL 或触发断言
 */
TEST_F(MrtkMutexTest, Mutex_Create_NullName_ReturnsNull) {
    // Step 1: Given - MRTK_NULL 名称参数
    // Step 2: When - 创建互斥量
    mrtk_mutex_t *mutex = mrtk_mutex_create(nullptr, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 预期返回 MRTK_NULL
    EXPECT_EQ(mutex, nullptr);
}

/* ==============================================================================
 * mrtk_mutex_delete() 测试用例
 * ============================================================================== */

/**
 * @test Mutex_Delete_ValidDynamicMutex_Success
 * @brief 测试正常删除动态互斥量
 * @details 验证删除后互斥量内存被释放
 * @Given 动态创建的互斥量
 * @When 调用 mrtk_mutex_delete()
 * @Then 返回 MRTK_EOK，内存被释放
 */
TEST_F(MrtkMutexTest, Mutex_Delete_ValidDynamicMutex_Success) {
    // Step 1: Given - 创建动态互斥量
    test_mutex_dynamic = mrtk_mutex_create("TestMutex",
                                            MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    ASSERT_NE(test_mutex_dynamic, nullptr);

    // 保存指针用于验证释放（实际验证依赖 valgrind/ASan）
    mrtk_mutex_t *ptr_to_free = test_mutex_dynamic;

    // Step 2: When - 删除互斥量
    mrtk_err_t ret = mrtk_mutex_delete(test_mutex_dynamic);

    // Step 3: Then - 验证返回值
    EXPECT_EQ(ret, MRTK_EOK);
    test_mutex_dynamic = nullptr; /* 避免重复释放 */
}

/**
 * @test Mutex_Delete_Null_ReturnsError
 * @brief 测试删除 MRTK_NULL 互斥量（防御性测试）
 * @Given MRTK_NULL 互斥量指针
 * @When 调用 mrtk_mutex_delete()
 * @Then 返回错误或触发断言
 */
TEST_F(MrtkMutexTest, Mutex_Delete_Null_ReturnsError) {
    // Step 1: Given - MRTK_NULL 互斥量指针
    // Step 2: When - 执行删除
    mrtk_err_t ret = mrtk_mutex_delete(nullptr);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_mutex_take() 测试用例
 * ============================================================================== */

/**
 * @test Mutex_Take_UnlockedMutex_Success
 * @brief 测试获取未锁定的互斥量
 * @details 验证首次获取互斥量的行为
 * @Given 未锁定的互斥量和当前任务
 * @When 调用 mrtk_mutex_take()
 * @Then 返回 MRTK_EOK，互斥量被锁定，持有者设为当前任务
 */
TEST_F(MrtkMutexTest, Mutex_Take_UnlockedMutex_Success) {
    // Step 1: Given - 初始化互斥量并设置当前任务
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 获取互斥量
    mrtk_err_t ret = mrtk_mutex_take(&test_mutex_static, 100);

    // Step 3: Then - 验证互斥量状态
    EXPECT_EQ(ret, MRTK_EOK);
    verify_mutex_state(&test_mutex_static, MRTK_MUTEX_STATE_LOCKED, 1, &task_high,
                       PRIO_HIGH);
}

/**
 * @test Mutex_Take_RecursiveLock_SameTask_Succeeds
 * @brief 测试递归锁（同任务多次获取）
 * @details 验证同一任务多次获取互斥量时 nest 计数增加
 * @Given 互斥量已被当前任务持有
 * @When 再次调用 mrtk_mutex_take()
 * @Then 返回 MRTK_EOK，nest 计数增加，不阻塞
 */
TEST_F(MrtkMutexTest, Mutex_Take_RecursiveLock_SameTask_Succeeds) {
    // Step 1: Given - 当前任务已持有互斥量
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);
    mrtk_mutex_take(&test_mutex_static, 100);
    ASSERT_EQ(test_mutex_static.nest, 1);

    // Step 2: When - 同一任务再次获取
    mrtk_err_t ret = mrtk_mutex_take(&test_mutex_static, 100);

    // Step 3: Then - 验证 nest 计数增加
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mutex_static.nest, 2);
    EXPECT_EQ(test_mutex_static.owner_task, &task_high);
}

/**
 * @test Mutex_Take_MaxNestCount_OverflowBoundary
 * @brief 测试递归锁边界值（nest 计数最大值）
 * @details 验证 nest 计数达到 255 时再获取的行为（溢出边界）
 * @Given 互斥量 nest 计数为 255
 * @When 再次调用 mrtk_mutex_take()
 * @Then nest 计数溢出回 0（验证溢出处理或限制）
 */
TEST_F(MrtkMutexTest, Mutex_Take_MaxNestCount_OverflowBoundary) {
    // Step 1: Given - nest 计数达到最大值
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);
    mrtk_mutex_take(&test_mutex_static, 0);

    // 直接设置 nest 为最大值（模拟多次递归）
    test_mutex_static.nest = 255;

    // Step 2: When - 再次获取（触发溢出）
    mrtk_err_t ret = mrtk_mutex_take(&test_mutex_static, 100);

    // Step 3: Then - 验证溢出行为（nest 回绕到 0）
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mutex_static.nest, 0); /* 255 + 1 溢出为 0 */
}

/**
 * @test Mutex_Take_LockedMutex_ZeroTimeout_ImmediateReturn
 * @brief 测试非阻塞获取已锁定的互斥量
 * @details 验证 timeout=0 时立即返回错误
 * @Given 互斥量被其他任务持有
 * @When 以 timeout=0 调用 mrtk_mutex_take()
 * @then 返回 MRTK_ERROR（不阻塞）
 */
TEST_F(MrtkMutexTest, Mutex_Take_LockedMutex_ZeroTimeout_ImmediateReturn) {
    // Step 1: Given - 低优先级任务持有互斥量
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_low);
    make_task_ready(&task_low);
    mrtk_mutex_take(&test_mutex_static, 0);

    // 切换到高优先级任务
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 尝试非阻塞获取
    mrtk_err_t ret = mrtk_mutex_take(&test_mutex_static, 0);

    // Step 3: Then - 验证立即返回错误
    EXPECT_EQ(ret, MRTK_EEMPTY);
    EXPECT_EQ(test_mutex_static.owner_task, &task_low); /* 持有者不变 */
}

/**
 * @test Mutex_Take_InInterruptContext_WithTimeout_ReturnsError
 * @brief 测试中断上下文中阻塞获取
 * @details 验证在中断中调用带 timeout 的 take 会返回错误
 * @Given 在中断上下文中（g_interrupt_nest > 0）
 * @When 以 timeout > 0 调用 mrtk_mutex_take()
 * @then 返回 MRTK_ERROR
 */
TEST_F(MrtkMutexTest, Mutex_Take_InInterruptContext_WithTimeout_ReturnsError) {
    // Step 1: Given - 模拟中断上下文
    set_interrupt_nest(1);
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 在中断中尝试阻塞获取
    mrtk_err_t ret = mrtk_mutex_take(&test_mutex_static, 100);

    // Step 3: Then - 验证返回错误
    EXPECT_EQ(ret, MRTK_E_IN_ISR);

    // 恢复中断嵌套
    set_interrupt_nest(0);
}

/**
 * @test Mutex_Take_InInterruptContext_ZeroTimeout_Succeeds
 * @brief 测试中断上下文中非阻塞获取
 * @details 验证在中断中以 timeout=0 获取可以成功
 * @Given 在中断上下文中且互斥量未锁定
 * @When 以 timeout=0 调用 mrtk_mutex_take()
 * @then 返回 MRTK_EOK
 */
TEST_F(MrtkMutexTest, Mutex_Take_InInterruptContext_ZeroTimeout_Succeeds) {
    // Step 1: Given - 模拟中断上下文
    set_interrupt_nest(1);
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 在中断中尝试非阻塞获取
    mrtk_err_t ret = mrtk_mutex_take(&test_mutex_static, 0);

    // Step 3: Then - 验证成功获取
    EXPECT_EQ(ret, MRTK_EOK);

    // 恢复中断嵌套
    set_interrupt_nest(0);
}

/**
 * @test Mutex_Take_PriorityInheritance_OwnerPriorityRaised
 * @brief 测试优先级继承机制
 * @details 验证高优先级任务等待时，持有者优先级被提升
 * @Given 低优先级任务持有互斥量，高优先级任务尝试获取
 * @When 高优先级任务阻塞获取
 * @Then 低优先级任务的优先级被提升到高优先级
 */
TEST_F(MrtkMutexTest, Mutex_Take_PriorityInheritance_OwnerPriorityRaised) {
    // Step 1: Given - 低优先级任务持有互斥量
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_low);
    make_task_ready(&task_low);
    mrtk_mutex_take(&test_mutex_static, 0);

    // 验证初始状态
    ASSERT_EQ(task_low.priority, PRIO_LOW);
    ASSERT_EQ(test_mutex_static.orig_prio, PRIO_LOW);

    // 切换到高优先级任务
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 高优先级任务尝试获取（将触发优先级继承）
    // 注意：此测试仅验证优先级继承逻辑，不实际阻塞任务
    // 实际阻塞需要模拟调度器行为

    // Step 3: Then - 验证低优先级任务优先级被提升
    // 在实际执行中，_mrtk_schedule_prio_change() 会被调用
    // 这里验证逻辑分支的触发
}

/**
 * @test Mutex_Take_PriorityInheritance_NoInheritanceWhenPrioEqual
 * @brief 测试优先级相同时不触发继承
 * @details 验证等待任务优先级 <= 持有者时不触发优先级继承
 * @Given 中优先级任务持有互斥量，另一个中优先级任务尝试获取
 * @When 尝试获取
 * @Then 不触发优先级继承（持有者优先级不变）
 */
TEST_F(MrtkMutexTest, Mutex_Take_PriorityInheritance_NoInheritanceWhenPrioEqual) {
    // Step 1: Given - 中优先级任务持有互斥量
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_mid);
    make_task_ready(&task_mid);
    mrtk_mutex_take(&test_mutex_static, 0);

    mrtk_u8_t original_owner_prio = task_mid.priority;

    // 切换到另一个中优先级任务
    set_current_task(&task_high);
    task_high.priority = PRIO_MID; /* 修改为相同优先级 */
    make_task_ready(&task_high);

    // Step 2: When - 相同优先级任务尝试获取
    // 应该不触发优先级继承分支

    // Step 3: Then - 验证持有者优先级不变
    EXPECT_EQ(task_mid.priority, original_owner_prio);
}

/**
 * @test Mutex_Take_Null_ReturnsError
 * @brief 测试获取 MRTK_NULL 互斥量（防御性测试）
 * @Given MRTK_NULL 互斥量指针
 * @When 调用 mrtk_mutex_take()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMutexTest, Mutex_Take_Null_ReturnsError) {
    // Step 1: Given - MRTK_NULL 互斥量指针
    set_current_task(&task_high);

    // Step 2: When - 执行获取
    mrtk_err_t ret = mrtk_mutex_take(nullptr, 100);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_mutex_trytake() 测试用例
 * ============================================================================== */

/**
 * @test Mutex_Trytake_UnlockedMutex_Success
 * @brief 测试非阻塞获取未锁定的互斥量
 * @details 验证 trytake 在互斥量可用时能成功获取
 * @Given 未锁定的互斥量
 * @When 调用 mrtk_mutex_trytake()
 * @Then 返回 MRTK_EOK，互斥量被锁定
 */
TEST_F(MrtkMutexTest, Mutex_Trytake_UnlockedMutex_Success) {
    // Step 1: Given - 未锁定的互斥量
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 尝试非阻塞获取
    mrtk_err_t ret = mrtk_mutex_trytake(&test_mutex_static);

    // Step 3: Then - 验证成功获取
    EXPECT_EQ(ret, MRTK_EOK);
    verify_mutex_state(&test_mutex_static, MRTK_MUTEX_STATE_LOCKED, 1, &task_high,
                       PRIO_HIGH);
}

/**
 * @test Mutex_Trytake_LockedMutex_ImmediateFailure
 * @brief 测试非阻塞获取已锁定的互斥量
 * @details 验证 trytake 在互斥量被占用时立即返回错误
 * @Given 被其他任务锁定的互斥量
 * @When 调用 mrtk_mutex_trytake()
 * @Then 返回 MRTK_ERROR
 */
TEST_F(MrtkMutexTest, Mutex_Trytake_LockedMutex_ImmediateFailure) {
    // Step 1: Given - 低优先级任务持有互斥量
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_low);
    make_task_ready(&task_low);
    mrtk_mutex_take(&test_mutex_static, 0);

    // 切换到高优先级任务
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 尝试非阻塞获取
    mrtk_err_t ret = mrtk_mutex_trytake(&test_mutex_static);

    // Step 3: Then - 验证立即返回错误
    EXPECT_EQ(ret, MRTK_EEMPTY);
    EXPECT_EQ(test_mutex_static.owner_task, &task_low);
}

/**
 * @test Mutex_Trytake_Null_ReturnsError
 * @brief 测试 trytake MRTK_NULL 互斥量（防御性测试）
 * @Given MRTK_NULL 互斥量指针
 * @When 调用 mrtk_mutex_trytake()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMutexTest, Mutex_Trytake_Null_ReturnsError) {
    // Step 1: Given - MRTK_NULL 互斥量指针
    set_current_task(&task_high);

    // Step 2: When - 执行 trytake
    mrtk_err_t ret = mrtk_mutex_trytake(nullptr);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_mutex_release() 测试用例
 * ============================================================================== */

/**
 * @test Mutex_Release_OwnerReleases_Success
 * @brief 测试持有者正常释放互斥量
 * @details 验证释放后互斥量变为未锁定状态
 * @Given 当前任务持有互斥量
 * @When 调用 mrtk_mutex_release()
 * @Then 返回 MRTK_EOK，互斥量变为未锁定
 */
TEST_F(MrtkMutexTest, Mutex_Release_OwnerReleases_Success) {
    // Step 1: Given - 当前任务持有互斥量
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);
    mrtk_mutex_take(&test_mutex_static, 0);
    ASSERT_EQ(test_mutex_static.nest, 1);

    // Step 2: When - 释放互斥量
    mrtk_err_t ret = mrtk_mutex_release(&test_mutex_static);

    // Step 3: Then - 验证互斥量状态
    EXPECT_EQ(ret, MRTK_EOK);
    verify_mutex_state(&test_mutex_static, MRTK_MUTEX_STATE_UNLOCKED, 0, nullptr, MRTK_INVALID_U8);
}

/**
 * @test Mutex_Release_RecursiveLock_DecrementsNest
 * @brief 测试递归锁释放
 * @details 验证递归锁释放时 nest 计数递减，不立即释放
 * @Given 互斥量 nest 计数 > 1
 * @When 调用 mrtk_mutex_release()
 * @Then 返回 MRTK_EOK，nest 计数减 1，互斥量仍被持有
 */
TEST_F(MrtkMutexTest, Mutex_Release_RecursiveLock_DecrementsNest) {
    // Step 1: Given - 递归获取 3 次
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);
    mrtk_mutex_take(&test_mutex_static, 100);
    mrtk_mutex_take(&test_mutex_static, 100);
    mrtk_mutex_take(&test_mutex_static, 100);
    ASSERT_EQ(test_mutex_static.nest, 3);

    // Step 2: When - 释放一次
    mrtk_err_t ret = mrtk_mutex_release(&test_mutex_static);

    // Step 3: Then - 验证 nest 计数递减，但仍被持有
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mutex_static.nest, 2);
    EXPECT_EQ(test_mutex_static.value, MRTK_MUTEX_STATE_LOCKED);
    EXPECT_EQ(test_mutex_static.owner_task, &task_high);
}

/**
 * @test Mutex_Release_NonOwner_ReturnsError
 * @brief 测试非持有者释放互斥量
 * @details 验证非持有者尝试释放时返回错误
 * @Given 互斥量被任务 A 持有，当前任务为 B
 * @When 任务 B 调用 mrtk_mutex_release()
 * @Then 返回 MRTK_ERROR
 */
TEST_F(MrtkMutexTest, Mutex_Release_NonOwner_ReturnsError) {
    // Step 1: Given - 低优先级任务持有互斥量
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_low);
    make_task_ready(&task_low);
    mrtk_mutex_take(&test_mutex_static, 0);
    ASSERT_EQ(test_mutex_static.owner_task, &task_low);

    // 切换到高优先级任务（非持有者）
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 非持有者尝试释放
    mrtk_err_t ret = mrtk_mutex_release(&test_mutex_static);

    // Step 3: Then - 验证返回错误
    EXPECT_EQ(ret, MRTK_ERROR);
    EXPECT_EQ(test_mutex_static.owner_task, &task_low); /* 持有者不变 */
}

/**
 * @test Mutex_Release_WithWaitingTasks_WakeupOneTask
 * @brief 测试释放时有等待任务的情况
 * @details 验证释放时唤醒一个等待任务并转移所有权
 * @Given 互斥量被持有，且有任务在等待队列中
 * @When 持有者释放互斥量
 * @Then 等待队列中的一个任务被唤醒，成为新的持有者
 */
TEST_F(MrtkMutexTest, Mutex_Release_WithWaitingTasks_WakeupOneTask) {
    // Step 1: Given - 低优先级任务持有互斥量，高优先级任务等待
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_low);
    make_task_ready(&task_low);
    mrtk_mutex_take(&test_mutex_static, 0);

    // 将高优先级任务挂起到等待队列
    make_task_suspend(&task_high);
    task_high.last_error = MRTK_EOK;
    _mrtk_list_insert_before(&test_mutex_static.ipc_obj.suspend_taker,
                          &task_high.sched_node);

    // Step 2: When - 低优先级任务释放互斥量
    mrtk_err_t ret = mrtk_mutex_release(&test_mutex_static);

    // Step 3: Then - 验证高优先级任务被唤醒并成为新持有者
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mutex_static.owner_task, &task_high);
    EXPECT_EQ(test_mutex_static.nest, 1);
    EXPECT_EQ(test_mutex_static.orig_prio, PRIO_HIGH);
}

/**
 * @test Mutex_Release_RestoresOriginalPriority
 * @brief 测试释放时恢复持有者原始优先级
 * @details 验证互斥量释放后，持有者的优先级能够正确恢复到原始值
 * @Given 低优先级任务持有互斥量，且发生过优先级继承（优先级被提升）
 * @When 持有者任务释放互斥量
 * @Then 持有者的优先级恢复到原始值，互斥量状态正确
 */
TEST_F(MrtkMutexTest, Mutex_Release_RestoresOriginalPriority) {
    /* Step 1: Given - 低优先级任务持有互斥量，且发生过优先级继承 */
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    /* 低优先级任务获取互斥量 */
    set_current_task(&task_low);
    make_task_ready(&task_low);
    mrtk_mutex_take(&test_mutex_static, 0);

    /* 验证初始状态 */
    verify_mutex_state(&test_mutex_static, MRTK_MUTEX_STATE_LOCKED, 1, &task_low,
                       PRIO_LOW);
    verify_task_priority(&task_low, PRIO_LOW);
    EXPECT_EQ(task_low.orig_prio, PRIO_LOW); /* 原始优先级 */

    /* 模拟高优先级任务等待触发优先级继承 */
    /* 方法：手动提升低优先级任务的优先级，模拟优先级继承场景 */
    test_mutex_static.orig_prio = PRIO_LOW;  /* 互斥量记录的原始优先级 */
    task_low.priority         = PRIO_HIGH;   /* 被提升到高优先级 */

    /* 验证优先级已被提升 */
    verify_task_priority(&task_low, PRIO_HIGH);

    /* Step 2: When - 低优先级任务释放互斥量 */
    mrtk_err_t ret = mrtk_mutex_release(&test_mutex_static);

    mrtk_task_dump(&task_low);
    /* Step 3: Then - 验证返回值和优先级恢复 */
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(task_low.priority, PRIO_LOW);     /* 恢复到原始优先级 */
    EXPECT_EQ(task_low.orig_prio, PRIO_LOW);    /* 原始优先级不变 */

    /* 验证互斥量状态：已释放，无持有者 */
    verify_mutex_state(&test_mutex_static, MRTK_MUTEX_STATE_UNLOCKED, 0, nullptr,
                       MRTK_INVALID_U8);

    /* 验证任务不再持有互斥量（通过检查链表是否为空） */
    EXPECT_TRUE(_mrtk_list_is_empty(&task_low.held_mutex_list));
}

/**
 * @test Mutex_Release_Null_ReturnsError
 * @brief 测试释放 MRTK_NULL 互斥量（防御性测试）
 * @Given MRTK_NULL 互斥量指针
 * @When 调用 mrtk_mutex_release()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMutexTest, Mutex_Release_Null_ReturnsError) {
    // Step 1: Given - MRTK_NULL 互斥量指针
    set_current_task(&task_high);

    // Step 2: When - 执行释放
    mrtk_err_t ret = mrtk_mutex_release(nullptr);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_mutex_control() 测试用例
 * ============================================================================== */

/**
 * @test Mutex_Control_GetOwner_ReturnsCorrectOwner
 * @brief 测试控制接口：查询持有者任务
 * @details 验证 MRTK_MUTEX_CMD_GET_OWNER 命令正确返回持有者任务
 * @Given 持有者任务已获取互斥量
 * @When 调用 mrtk_mutex_control() 查询持有者
 * @Then 返回正确的持有者任务指针
 */
TEST_F(MrtkMutexTest, Mutex_Control_GetOwner_ReturnsCorrectOwner) {
    /* Step 1: Given - 高优先级任务持有互斥量 */
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    set_current_task(&task_high);
    make_task_ready(&task_high);
    mrtk_mutex_take(&test_mutex_static, 0);

    /* Step 2: When - 查询持有者任务 */
    mrtk_task_t *owner = nullptr;
    mrtk_err_t ret = mrtk_mutex_control(&test_mutex_static,
                                       MRTK_MUTEX_CMD_GET_OWNER, &owner);

    /* Step 3: Then - 验证返回正确的持有者 */
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(owner, &task_high);
}

/**
 * @test Mutex_Control_GetNest_ReturnsCorrectDepth
 * @brief 测试控制接口：查询递归嵌套深度
 * @details 验证 MRTK_MUTEX_CMD_GET_NEST 命令正确返回嵌套深度
 * @Given 持有者任务多次获取同一互斥量
 * @When 调用 mrtk_mutex_control() 查询嵌套深度
 * @Then 返回正确的嵌套深度
 */
TEST_F(MrtkMutexTest, Mutex_Control_GetNest_ReturnsCorrectDepth) {
    /* Step 1: Given - 任务多次获取互斥量（递归锁） */
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_mutex_take(&test_mutex_static, 0);  /* nest = 1 */
    mrtk_mutex_take(&test_mutex_static, 0);  /* nest = 2 */
    mrtk_mutex_take(&test_mutex_static, 0);  /* nest = 3 */

    /* Step 2: When - 查询递归嵌套深度 */
    mrtk_u8_t nest = 0;
    mrtk_err_t ret = mrtk_mutex_control(&test_mutex_static,
                                       MRTK_MUTEX_CMD_GET_NEST, &nest);

    /* Step 3: Then - 验证返回正确的嵌套深度 */
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(nest, 3);
}

/**
 * @test Mutex_Control_GetOrigPrio_ReturnsCorrectPriority
 * @brief 测试控制接口：查询原始优先级
 * @details 验证 MRTK_MUTEX_CMD_GET_ORIG_PRIO 命令正确返回原始优先级
 * @Given 持有者任务的优先级已被继承提升
 * @When 调用 mrtk_mutex_control() 查询原始优先级
 * @Then 返回持有者的原始优先级（未提升前的优先级）
 */
TEST_F(MrtkMutexTest, Mutex_Control_GetOrigPrio_ReturnsCorrectPriority) {
    /* Step 1: Given - 低优先级任务持有互斥量，优先级被提升 */
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    set_current_task(&task_low);
    make_task_ready(&task_low);
    mrtk_mutex_take(&test_mutex_static, 0);  /* orig_prio 被保存为 PRIO_LOW */

    /* 模拟优先级继承（提升到 PRIO_HIGH） */
    test_mutex_static.orig_prio = PRIO_LOW;
    task_low.priority = PRIO_HIGH;

    /* Step 2: When - 查询原始优先级 */
    mrtk_u8_t orig_prio = 0xFF;
    mrtk_err_t ret = mrtk_mutex_control(&test_mutex_static,
                                       MRTK_MUTEX_CMD_GET_ORIG_PRIO, &orig_prio);

    /* Step 3: Then - 验证返回原始优先级（而非当前优先级） */
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(orig_prio, PRIO_LOW);
    EXPECT_NE(task_low.priority, PRIO_LOW);  /* 当前优先级已被提升 */
}

/**
 * @test Mutex_Control_InvalidParameters_ReturnsError
 * @brief 测试控制接口：无效参数处理
 * @details 验证 control 函数对无效参数返回错误
 * @Given 初始化的互斥量
 * @When 使用 MRTK_NULL 指针或无效命令调用 control
 * @Then 返回 MRTK_EINVAL 或 MRTK_ERROR
 */
TEST_F(MrtkMutexTest, Mutex_Control_InvalidParameters_ReturnsError) {
    /* Step 1: Given - 初始化互斥量 */
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    /* Step 2: When - 使用各种无效参数调用 control */

    /* 2.1 MRTK_NULL 互斥量指针 */
    mrtk_err_t ret1 = mrtk_mutex_control(nullptr, MRTK_MUTEX_CMD_GET_OWNER, nullptr);

    /* 2.2 MRTK_NULL arg 参数（GET_OWNER 命令） */
    mrtk_task_t *owner = nullptr;
    mrtk_err_t ret2 = mrtk_mutex_control(&test_mutex_static,
                                        MRTK_MUTEX_CMD_GET_OWNER, nullptr);

    /* 2.3 MRTK_NULL arg 参数（GET_NEST 命令） */
    mrtk_err_t ret3 = mrtk_mutex_control(&test_mutex_static,
                                        MRTK_MUTEX_CMD_GET_NEST, nullptr);

    /* 2.4 无效命令 */
    mrtk_u8_t dummy = 0;
    mrtk_err_t ret4 = mrtk_mutex_control(&test_mutex_static, 0xFF, &dummy);

    /* Step 3: Then - 验证返回错误码 */
    EXPECT_EQ(ret1, MRTK_EINVAL);  /* MRTK_NULL 互斥量 */
    EXPECT_EQ(ret2, MRTK_EINVAL);  /* MRTK_NULL arg (GET_OWNER) */
    EXPECT_EQ(ret3, MRTK_EINVAL);  /* MRTK_NULL arg (GET_NEST) */
    EXPECT_EQ(ret4, MRTK_ERROR);   /* 无效命令 */
}

/* ==============================================================================
 * 综合场景测试
 * ============================================================================== */

/**
 * @test Mutex_CompleteLifecycle_InitTakeReleaseDetach_Success
 * @brief 测试互斥量完整生命周期
 * @details 验证 Init → Take → Release → Detach 的完整流程
 * @Given 互斥量对象
 * @When 依次执行 init, take, release, detach
 * @Then 每一步都成功返回
 */
TEST_F(MrtkMutexTest, Mutex_CompleteLifecycle_InitTakeReleaseDetach_Success) {
    // Step 1: Given - 互斥量对象和任务

    // Step 2: When - 执行完整生命周期
    mrtk_err_t ret_init = mrtk_mutex_init(&test_mutex_static, "LifecycleMutex",
                                           MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);
    mrtk_err_t ret_take = mrtk_mutex_take(&test_mutex_static, 100);
    mrtk_err_t ret_release = mrtk_mutex_release(&test_mutex_static);
    mrtk_err_t ret_detach = mrtk_mutex_detach(&test_mutex_static);

    // Step 3: Then - 验证每一步都成功
    EXPECT_EQ(ret_init, MRTK_EOK);
    EXPECT_EQ(ret_take, MRTK_EOK);
    EXPECT_EQ(ret_release, MRTK_EOK);
    EXPECT_EQ(ret_detach, MRTK_EOK);
}

/**
 * @test Mutex_MultipleTasksWaiting_PriorityOrderWakeup
 * @brief 测试多任务等待时的唤醒顺序
 * @details 验证 PRIO 策略下按优先级顺序唤醒
 * @Given 互斥量被持有，3 个不同优先级的任务在等待
 * @When 持有者释放互斥量
 * @Then 最高优先级的等待任务被唤醒
 */
TEST_F(MrtkMutexTest, Mutex_MultipleTasksWaiting_PriorityOrderWakeup) {
    /* Step 1: Given - 低优先级任务持有互斥量，3 个任务在等待队列 */

    /* 1.1 初始化互斥量并让低优先级任务持有 */
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_low);
    make_task_ready(&task_low);
    mrtk_mutex_take(&test_mutex_static, 0);

    /* 1.2 将三个任务按任意顺序挂起到等待队列
     *     使用 _mrtk_ipc_suspend_one() 并传入 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO
     *     函数会自动按优先级降序排序队列（高优先级在头部）
     */
    make_task_ready(&task_mid);
    _mrtk_ipc_suspend_one(&test_mutex_static.ipc_obj.suspend_taker,
                          MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO, &task_mid);

    make_task_ready(&task_high);
    _mrtk_ipc_suspend_one(&test_mutex_static.ipc_obj.suspend_taker,
                          MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO, &task_high);

    /* 创建另一个低优先级任务 */
    mrtk_task_t task_low_2;
    mrtk_u32_t task_stack_low_2[512];
    mrtk_task_init("TaskLow2", &task_low_2, dummy_task_entry, nullptr,
                   task_stack_low_2, 512, PRIO_LOW + 1, 10);
    make_task_ready(&task_low_2);
    _mrtk_ipc_suspend_one(&test_mutex_static.ipc_obj.suspend_taker,
                          MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO, &task_low_2);

    /* Step 2: When - 持有者释放互斥量 */
    set_current_task(&task_low);  /* 确保在持有者任务的上下文 */
    mrtk_err_t ret = mrtk_mutex_release(&test_mutex_static);

    /* Step 3: Then - 验证高优先级任务被唤醒
     *     由于使用了 PRIO 策略，_mrtk_ipc_suspend_one() 会自动排序
     *     队列顺序应为：task_high -> task_mid -> task_low_2（按优先级降序）
     *     mrtk_mutex_release() 调用 _mrtk_ipc_resume_one() 从队列头部取任务
     *     因此应该唤醒 task_high（最高优先级）
     */
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mutex_static.owner_task, &task_high);
    EXPECT_EQ(test_mutex_static.orig_prio, PRIO_HIGH);
}

/**
 * @test Mutex_FIFO_WaitingOrder_FIFOWakeup
 * @brief 测试 FIFO 策略下的唤醒顺序
 * @details 验证 FIFO 策略按等待顺序唤醒
 * @Given 使用 FIFO 策略的互斥量，多个任务在等待
 * @When 持有者释放互斥量
 * @Then 按照等待顺序（先来先得）唤醒任务
 */
TEST_F(MrtkMutexTest, Mutex_FIFO_WaitingOrder_FIFOWakeup) {
    // Step 1: Given - FIFO 策略互斥量，3 个任务按顺序等待
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_FIFO);
    set_current_task(&task_low);
    make_task_ready(&task_low);
    mrtk_mutex_take(&test_mutex_static, 0);

    // 按顺序插入等待队列
    make_task_suspend(&task_mid);
    _mrtk_list_insert_before(&test_mutex_static.ipc_obj.suspend_taker,
                          &task_mid.sched_node);

    make_task_suspend(&task_high);
    _mrtk_list_insert_before(&test_mutex_static.ipc_obj.suspend_taker,
                          &task_high.sched_node);

    make_task_suspend(&task_low);
    _mrtk_list_insert_before(&test_mutex_static.ipc_obj.suspend_taker,
                          &task_low.sched_node);

    // Step 2: When - 持有者释放互斥量
    mrtk_err_t ret = mrtk_mutex_release(&test_mutex_static);

    // Step 3: Then - 验证第一个等待者（中优先级任务）被唤醒
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mutex_static.owner_task, &task_mid);
    EXPECT_EQ(test_mutex_static.orig_prio, PRIO_MID);
}

/**
 * @test Mutex_InterruptContext_NonBlockingOperations_Only
 * @brief 测试中断上下文中的互斥量操作限制
 * @details 验证中断中只能进行非阻塞操作
 * @Given 在中断上下文中
 * @When 尝试阻塞操作 vs 非阻塞操作
 * @Then 阻塞操作返回错误，非阻塞操作成功
 */
/**
 * @test Mutex_InterruptContext_NonBlockingOperations_Only
 * @brief 测试中断上下文中只允许非阻塞操作
 * @details 验证中断上下文中只允许非阻塞获取，阻塞操作和释放都被禁止
 * @Given 中断上下文
 * @When 在中断中尝试各种操作
 * @Then 只有非阻塞获取成功，其他操作都返回 MRTK_E_IN_ISR
 */
TEST_F(MrtkMutexTest, Mutex_InterruptContext_NonBlockingOperations_Only) {
    /* Step 1: Given - 中断上下文 */
    set_interrupt_nest(1);
    mrtk_mutex_init(&test_mutex_static, "TestMutex",
                    MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    /* Step 2: When - 在中断中尝试各种操作 */
    mrtk_err_t ret_nonblock = mrtk_mutex_take(&test_mutex_static, 0);   /* 允许：非阻塞 */
    mrtk_err_t ret_block    = mrtk_mutex_take(&test_mutex_static, 100); /* 禁止：阻塞 */
    mrtk_err_t ret_release  = mrtk_mutex_release(&test_mutex_static);  /* 禁止：释放 */

    /* Step 3: Then - 验证结果 */
    EXPECT_EQ(ret_nonblock, MRTK_EOK);         /* 非阻塞获取成功 */
    EXPECT_EQ(ret_block, MRTK_E_IN_ISR);       /* 阻塞获取被禁止 */
    EXPECT_EQ(ret_release, MRTK_E_IN_ISR);     /* 释放也被禁止（互斥量不适合中断） */

    /* 恢复中断嵌套 */
    set_interrupt_nest(0);
}

#endif /* (MRTK_USING_MUTEX == 1) */
