/**
 * @file mrtk_sem_test.cpp
 * @author leiyx (Generated by SDET Architecture)
 * @brief 信号量模块单元测试套件
 * @details 严格遵循 BDD 风格（Given-When-Then），覆盖边界值、等价类、分支覆盖和状态机
 *
 * 测试覆盖策略：
 * 1. 边界值分析：value=0/UINT16_MAX、timeout=0/MRTK_WAIT_FOREVER、资源计数回卷
 * 2. 等价类划分：NULL参数、非法对象类型、静态/动态对象、FIFO/PRIO策略
 * 3. 分支覆盖：中断上下文分支、资源计数>0分支、等待队列空/满分支
 * 4. 状态机覆盖：INIT → TAKE → RELEASE → DETACH/DELETE 全生命周期
 * 5. 并发场景：多任务等待、资源耗尽、二值信号量模式
 * @copyright Copyright (c) 2026
 */


#include <gtest/gtest.h>
#include <gmock/gmock.h>

/* Mock 头文件（C++ 代码，必须在最前） */
#include "mrtk_mock_hw.hpp"

#if (MRTK_USING_SEMAPHORE == 1)

/* MRTK 头文件（已包含 extern "C"） */
#include "mrtk.h"

/* ==============================================================================
 * 测试夹具：MrtkSemTest
 * ============================================================================== */

/**
 * @class MrtkSemTest
 * @brief 信号量模块测试夹具
 * @details 提供 Mock 环境、系统初始化和辅助方法
 */
class MrtkSemTest : public ::testing::Test {
  protected:
    /* Mock 对象（使用 NiceMock 自动忽略未设置期望的调用，避免 GMOCK WARNING） */
    testing::NiceMock<MockCpuPort> mock_cpu_port;

    /* 测试用信号量对象 */
    mrtk_sem_t test_sem_static;
    mrtk_sem_t *test_sem_dynamic = nullptr;

    /* 测试用任务对象（静态分配栈内存） */
    static constexpr mrtk_u32_t TASK_STACK_SIZE = 512;
    mrtk_u32_t task_stack_high[512];
    mrtk_u32_t task_stack_mid[512];
    mrtk_u32_t task_stack_low[512];
    mrtk_task_t task_high;
    mrtk_task_t task_mid;
    mrtk_task_t task_low;

#if (MRTK_PRIO_HIGHER_IS_LOWER_VALUE == 1)
    static constexpr mrtk_u8_t PRIO_HIGH = 5;
    static constexpr mrtk_u8_t PRIO_MID  = 10;
    static constexpr mrtk_u8_t PRIO_LOW  = 20;
#else 
    static constexpr mrtk_u8_t PRIO_HIGH = 20;
    static constexpr mrtk_u8_t PRIO_MID  = 10;
    static constexpr mrtk_u8_t PRIO_LOW  = 5;
#endif

    /* 任务入口函数（空实现，仅用于测试） */
    static mrtk_void_t dummy_task_entry(mrtk_void_t *param) {
        (void)param;
        /* 测试任务不会实际运行，仅验证状态管理 */
    }

  protected:
    /**
     * @brief 测试环境初始化
     * @details 执行顺序：系统初始化 → 设置 Mock → 设置默认行为 → 初始化测试对象
     */
    void SetUp() override {
        /* Step 1: 系统初始化（复位全局变量） */
        mrtk_system_init();

        g_CurrentTCB = mrtk_task_get_idle();

        /* Step 2: 设置 Mock 对象 */
        mrtk_mock_set_cpu_port(&mock_cpu_port);

        /* Step 3: 设置默认期望行为（避免对中断控制产生不必要依赖） */
        ON_CALL(mock_cpu_port, mrtk_hw_interrupt_disable)
            .WillByDefault(testing::Return(0));
        ON_CALL(mock_cpu_port, mrtk_hw_interrupt_enable)
            .WillByDefault(testing::Return());
        ON_CALL(mock_cpu_port, mrtk_hw_context_switch_interrupt)
            .WillByDefault(testing::Return());

        /* Step 4: 初始化测试任务 */
        init_test_tasks();
    }

    /**
     * @brief 测试环境清理
     * @details 清除 Mock 对象，释放动态分配的资源
     */
    void TearDown() override {
        /* 释放动态创建的信号量 */
        if (test_sem_dynamic != nullptr) {
            mrtk_free(test_sem_dynamic);
            test_sem_dynamic = nullptr;
        }

        /* 清除 Mock 对象 */
        mrtk_mock_clear_cpu_port();
    }

    /**
     * @brief 初始化测试用任务
     * @details 创建高/中/低三个优先级的任务，用于测试多任务场景
     */
    void init_test_tasks(mrtk_void_t) {
        mrtk_task_init("TaskHigh", &task_high, dummy_task_entry, nullptr,
                       task_stack_high, TASK_STACK_SIZE, PRIO_HIGH, 10);
        mrtk_task_init("TaskMid", &task_mid, dummy_task_entry, nullptr,
                       task_stack_mid, TASK_STACK_SIZE, PRIO_MID, 10);
        mrtk_task_init("TaskLow", &task_low, dummy_task_entry, nullptr,
                       task_stack_low, TASK_STACK_SIZE, PRIO_LOW, 10);
    }

    /**
     * @brief 设置当前运行任务
     * @details 模拟指定任务正在运行，用于测试信号量操作
     * @param[in] task 要设置为当前运行的任务指针
     */
    void set_current_task(mrtk_task_t *task) {
        extern mrtk_tcb_t *volatile g_CurrentTCB;
        g_CurrentTCB = task;
    }

    /**
     * @brief 设置中断嵌套层数
     * @details 模拟中断嵌套，用于测试中断上下文中的信号量操作
     * @param[in] nest 中断嵌套层数
     */
    void set_interrupt_nest(mrtk_u8_t nest) {
        extern volatile mrtk_u8_t g_interrupt_nest;
        g_interrupt_nest = nest;
    }

    /**
     * @brief 验证信号量状态
     * @details 断言信号量的资源计数值是否符合预期
     * @param[in] sem   信号量指针
     * @param[in] value 期望的资源计数值
     */
    void verify_sem_value(mrtk_sem_t *sem, mrtk_u16_t value) {
        EXPECT_EQ(sem->value, value);
    }

    /**
     * @brief 设置任务为就绪状态
     * @details 将任务插入对应优先级的就绪队列，用于测试任务恢复
     * @param[in] task 要设置为就绪的任务
     */
    void make_task_ready(mrtk_task_t *task) {
        task->state = MRTK_TASK_STAT_READY;
        _mrtk_schedule_insert_task(task);
    }

    /**
     * @brief 设置任务为挂起状态
     * @details 将任务从就绪队列移除并标记为挂起，用于测试任务阻塞
     * @param[in] task 要设置为挂起的任务
     */
    void make_task_suspend(mrtk_task_t *task) {
        _mrtk_schedule_remove_task(task);
        task->state = MRTK_TASK_STAT_SUSPEND;
    }
};

/* ==============================================================================
 * mrtk_sem_init() 测试用例
 * ============================================================================== */

/**
 * @test Sem_Init_ValidParameters_Success
 * @brief 测试正常初始化信号量
 * @details 验证信号量初始化后所有字段是否正确设置
 * @Given 有效的信号量指针、名称和初始值
 * @When 调用 mrtk_sem_init()
 * @Then 返回 MRTK_EOK，信号量值正确设置
 */
TEST_F(MrtkSemTest, Sem_Init_ValidParameters_Success) {
    // Step 1: Given - 准备有效的信号量对象和参数
    const mrtk_char_t *sem_name = "TestSem";
    mrtk_u16_t initial_value = 5;
    mrtk_u8_t flag = MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO;

    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_sem_init(&test_sem_static, sem_name, initial_value, flag);

    // Step 3: Then - 验证返回值和信号量值
    EXPECT_EQ(ret, MRTK_EOK);
    verify_sem_value(&test_sem_static, initial_value);
}

/**
 * @test Sem_Init_ZeroValue_Success
 * @brief 测试初始化零值信号量（边界值）
 * @details 验证初始值为 0 的信号量（二值信号量或同步信号量）
 * @Given 初始值为 0
 * @When 调用 mrtk_sem_init()
 * @Then 返回 MRTK_EOK，信号量值为 0
 */
TEST_F(MrtkSemTest, Sem_Init_ZeroValue_Success) {
    // Step 1: Given - 初始值为 0
    const mrtk_char_t *sem_name = "BinarySem";
    mrtk_u16_t initial_value = 0;

    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_sem_init(&test_sem_static, sem_name, initial_value,
                                   MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 验证成功且值为 0
    EXPECT_EQ(ret, MRTK_EOK);
    verify_sem_value(&test_sem_static, 0);
}

/**
 * @test Sem_Init_MaxValue_Success
 * @brief 测试初始化最大值信号量（边界值）
 * @details 验证初始值为 UINT16_MAX 的信号量
 * @Given 初始值为 UINT16_MAX
 * @When 调用 mrtk_sem_init()
 * @Then 返回 MRTK_EOK，信号量值为 UINT16_MAX
 */
TEST_F(MrtkSemTest, Sem_Init_MaxValue_Success) {
    // Step 1: Given - 初始值为最大值
    const mrtk_char_t *sem_name = "MaxSem";
    mrtk_u16_t initial_value = UINT16_MAX;

    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_sem_init(&test_sem_static, sem_name, initial_value,
                                   MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 验证成功且值为最大
    EXPECT_EQ(ret, MRTK_EOK);
    verify_sem_value(&test_sem_static, UINT16_MAX);
}

/**
 * @test Sem_Init_Null_ReturnsError
 * @brief 测试 MRTK_NULL 信号量指针（防御性测试）
 * @details 验证传入 MRTK_NULL 信号量指针时的行为
 * @Given MRTK_NULL 信号量指针
 * @When 调用 mrtk_sem_init()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkSemTest, Sem_Init_Null_ReturnsError) {
    // Step 1: Given - MRTK_NULL 信号量指针
    const mrtk_char_t *sem_name = "TestSem";

    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_sem_init(nullptr, sem_name, 1, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test Sem_Init_NullName_ReturnsError
 * @brief 测试 MRTK_NULL 名称参数（防御性测试）
 * @details 验证传入 MRTK_NULL 名称时的行为
 * @Given MRTK_NULL 名称参数
 * @When 调用 mrtk_sem_init()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkSemTest, Sem_Init_NullName_ReturnsError) {
    // Step 1: Given - MRTK_NULL 名称参数
    mrtk_sem_t sem;

    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_sem_init(&sem, nullptr, 1, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test Sem_Init_DifferentFlagTypes_Success
 * @brief 测试不同唤醒策略标志
 * @details 验证 FIFO 和 PRIO 两种唤醒策略都能正确初始化
 * @Given 有效的信号量对象和不同的 flag 值
 * @When 分别使用 FIFO 和 PRIO 标志初始化
 * @Then 初始化成功，flag 值正确保存
 */
TEST_F(MrtkSemTest, Sem_Init_DifferentFlagTypes_Success) {
    // Step 1: Given - 有效的信号量对象
    const mrtk_char_t *sem_name = "TestSem";

    // Step 2: When - 分别使用 FIFO 和 PRIO 标志初始化
    mrtk_err_t ret_fifo = mrtk_sem_init(&test_sem_static, sem_name, 1,
                                         MRTK_IPC_FLAG_NOTIFY_POLICY_FIFO);
    mrtk_err_t ret_prio = mrtk_sem_init(&test_sem_static, sem_name, 1,
                                         MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 两次初始化都应成功
    EXPECT_EQ(ret_fifo, MRTK_EOK);
    EXPECT_EQ(ret_prio, MRTK_EOK);
}

/* ==============================================================================
 * mrtk_sem_detach() 测试用例
 * ============================================================================== */

/**
 * @test Sem_Detach_ValidSem_Success
 * @brief 测试正常脱离信号量
 * @details 验证脱离静态信号量后的状态
 * @Given 已初始化的静态信号量
 * @When 调用 mrtk_sem_detach()
 * @Then 返回 MRTK_EOK，所有等待任务被唤醒并设置错误码
 */
TEST_F(MrtkSemTest, Sem_Detach_ValidSem_Success) {
    // Step 1: Given - 初始化信号量
    mrtk_sem_init(&test_sem_static, "TestSem", 1,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 脱离信号量
    mrtk_err_t ret = mrtk_sem_detach(&test_sem_static);

    // Step 3: Then - 验证返回值
    EXPECT_EQ(ret, MRTK_EOK);
}

/**
 * @test Sem_Detach_WithWaitingTasks_TasksResumedWithError
 * @brief 测试脱离有等待任务的信号量
 * @details 验证脱离时唤醒所有等待任务并设置 MRTK_EDELETED 错误码
 * @Given 已初始化的信号量，且有任务在等待队列中
 * @When 调用 mrtk_sem_detach()
 * @Then 所有等待任务被唤醒，last_error 设置为 MRTK_EDELETED
 */
TEST_F(MrtkSemTest, Sem_Detach_WithWaitingTasks_TasksResumedWithError) {
    // Step 1: Given - 初始化信号量，并有任务在等待队列中
    mrtk_sem_init(&test_sem_static, "TestSem", 0,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // 将高优先级任务挂起到信号量的等待队列
    make_task_suspend(&task_high);
    task_high.last_error = MRTK_EOK;
    _mrtk_list_insert_before(&test_sem_static.ipc_obj.suspend_taker,
                          &task_high.sched_node);

    // 将中优先级任务也挂起到等待队列
    make_task_suspend(&task_mid);
    task_mid.last_error = MRTK_EOK;
    _mrtk_list_insert_before(&test_sem_static.ipc_obj.suspend_taker,
                          &task_mid.sched_node);

    // Step 2: When - 脱离信号量
    mrtk_err_t ret = mrtk_sem_detach(&test_sem_static);

    // Step 3: Then - 验证返回值和任务状态
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(task_high.last_error, MRTK_EDELETED);
    EXPECT_EQ(task_mid.last_error, MRTK_EDELETED);
}

/**
 * @test Sem_Detach_Null_ReturnsError
 * @brief 测试脱离 MRTK_NULL 信号量（防御性测试）
 * @Given MRTK_NULL 信号量指针
 * @When 调用 mrtk_sem_detach()
 * @Then 返回错误或触发断言
 */
TEST_F(MrtkSemTest, Sem_Detach_Null_ReturnsError) {
    // Step 1: Given - MRTK_NULL 信号量指针
    // Step 2: When - 执行脱离
    mrtk_err_t ret = mrtk_sem_detach(nullptr);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_sem_create() 测试用例
 * ============================================================================== */

/**
 * @test Sem_Create_ValidParameters_Success
 * @brief 测试正常创建动态信号量
 * @details 验证动态创建的信号量是否正确初始化
 * @Given 有效的信号量名称
 * @When 调用 mrtk_sem_create()
 * @Then 返回有效的信号量指针，状态正确
 */
TEST_F(MrtkSemTest, Sem_Create_ValidParameters_Success) {
    // Step 1: Given - 有效的信号量名称和初始值
    const mrtk_char_t *sem_name = "DynamicSem";
    mrtk_u16_t initial_value = 10;

    // Step 2: When - 创建动态信号量
    test_sem_dynamic = mrtk_sem_create(sem_name, initial_value,
                                        MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 验证返回指针和值
    ASSERT_NE(test_sem_dynamic, nullptr);
    verify_sem_value(test_sem_dynamic, initial_value);
}

/**
 * @test Sem_Create_ZeroValue_Success
 * @brief 测试创建零值动态信号量
 * @details 验证创建初始值为 0 的动态信号量
 * @Given 初始值为 0
 * @When 调用 mrtk_sem_create()
 * @Then 返回有效的信号量指针，值为 0
 */
TEST_F(MrtkSemTest, Sem_Create_ZeroValue_Success) {
    // Step 1: Given - 初始值为 0
    const mrtk_char_t *sem_name = "BinarySem";

    // Step 2: When - 创建动态信号量
    test_sem_dynamic = mrtk_sem_create(sem_name, 0,
                                        MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 验证成功且值为 0
    ASSERT_NE(test_sem_dynamic, nullptr);
    verify_sem_value(test_sem_dynamic, 0);
}

/* ==============================================================================
 * mrtk_sem_delete() 测试用例
 * ============================================================================== */

/**
 * @test Sem_Delete_ValidDynamicSem_Success
 * @brief 测试正常删除动态信号量
 * @details 验证删除后信号量内存被释放
 * @Given 动态创建的信号量
 * @When 调用 mrtk_sem_delete()
 * @Then 返回 MRTK_EOK，内存被释放
 */
TEST_F(MrtkSemTest, Sem_Delete_ValidDynamicSem_Success) {
    // Step 1: Given - 创建动态信号量
    test_sem_dynamic = mrtk_sem_create("TestSem", 1,
                                        MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    ASSERT_NE(test_sem_dynamic, nullptr);

    // Step 2: When - 删除信号量
    mrtk_err_t ret = mrtk_sem_delete(test_sem_dynamic);

    // Step 3: Then - 验证返回值
    EXPECT_EQ(ret, MRTK_EOK);
    test_sem_dynamic = nullptr; /* 避免重复释放 */
}

/**
 * @test Sem_Delete_WithWaitingTasks_TasksResumedWithError
 * @brief 测试删除有等待任务的信号量
 * @details 验证删除时唤醒所有等待任务并设置错误码
 * @Given 动态创建的信号量，且有任务在等待队列中
 * @When 调用 mrtk_sem_delete()
 * @Then 所有等待任务被唤醒，last_error 设置为 MRTK_EDELETED
 */
TEST_F(MrtkSemTest, Sem_Delete_WithWaitingTasks_TasksResumedWithError) {
    // Step 1: Given - 创建信号量并有任务等待
    test_sem_dynamic = mrtk_sem_create("TestSem", 0,
                                        MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // 将高优先级任务挂起到等待队列
    make_task_suspend(&task_high);
    task_high.last_error = MRTK_EOK;
    _mrtk_list_insert_before(&test_sem_dynamic->ipc_obj.suspend_taker,
                          &task_high.sched_node);

    // Step 2: When - 删除信号量
    mrtk_err_t ret = mrtk_sem_delete(test_sem_dynamic);

    // Step 3: Then - 验证返回值和任务状态
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(task_high.last_error, MRTK_EDELETED);
    test_sem_dynamic = nullptr;
}

/**
 * @test Sem_Delete_Null_ReturnsError
 * @brief 测试删除 MRTK_NULL 信号量（防御性测试）
 * @Given MRTK_NULL 信号量指针
 * @When 调用 mrtk_sem_delete()
 * @Then 返回错误或触发断言
 */
TEST_F(MrtkSemTest, Sem_Delete_Null_ReturnsError) {
    // Step 1: Given - MRTK_NULL 信号量指针
    // Step 2: When - 执行删除
    mrtk_err_t ret = mrtk_sem_delete(nullptr);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_sem_take() 测试用例
 * ============================================================================== */

/**
 * @test Sem_Take_AvailableResource_Success
 * @brief 测试获取可用资源的信号量
 * @details 验证资源计数大于 0 时能成功获取
 * @Given 信号量有可用资源（value > 0）
 * @When 调用 mrtk_sem_take()
 * @Then 返回 MRTK_EOK，资源计数减 1
 */
TEST_F(MrtkSemTest, Sem_Take_AvailableResource_Success) {
    // Step 1: Given - 初始化信号量，资源计数为 5
    mrtk_sem_init(&test_sem_static, "TestSem", 5,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 获取信号量
    mrtk_err_t ret = mrtk_sem_take(&test_sem_static, 100);

    // Step 3: Then - 验证成功且资源计数减 1
    EXPECT_EQ(ret, MRTK_EOK);
    verify_sem_value(&test_sem_static, 4);
}

/**
 * @test Sem_Take_LastAvailableResource_ResourceBecomesZero
 * @brief 测试获取最后一个可用资源（边界值）
 * @details 验证资源计数从 1 变为 0
 * @Given 信号量资源计数为 1
 * @When 调用 mrtk_sem_take()
 * @Then 返回 MRTK_EOK，资源计数变为 0
 */
TEST_F(MrtkSemTest, Sem_Take_LastAvailableResource_ResourceBecomesZero) {
    // Step 1: Given - 信号量资源计数为 1
    mrtk_sem_init(&test_sem_static, "TestSem", 1,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 获取最后一个资源
    mrtk_err_t ret = mrtk_sem_take(&test_sem_static, 100);

    // Step 3: Then - 验证成功且资源计数变为 0
    EXPECT_EQ(ret, MRTK_EOK);
    verify_sem_value(&test_sem_static, 0);
}

/**
 * @test Sem_Take_NoResource_ZeroTimeout_ImmediateFailure
 * @brief 测试无资源时非阻塞获取
 * @details 验证 timeout=0 时立即返回错误
 * @Given 信号量无可用资源（value = 0）
 * @When 以 timeout=0 调用 mrtk_sem_take()
 * @Then 返回 MRTK_ERROR（不阻塞）
 */
TEST_F(MrtkSemTest, Sem_Take_NoResource_ZeroTimeout_ImmediateFailure) {
    // Step 1: Given - 信号量资源计数为 0
    mrtk_sem_init(&test_sem_static, "TestSem", 0,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 尝试非阻塞获取
    mrtk_err_t ret = mrtk_sem_take(&test_sem_static, 0);

    // Step 3: Then - 验证立即返回错误
    EXPECT_EQ(ret, MRTK_ERROR);
    verify_sem_value(&test_sem_static, 0);
}

/**
 * @test Sem_Take_InInterruptContext_WithTimeout_ReturnsError
 * @brief 测试中断上下文中阻塞获取
 * @details 验证在中断中调用带 timeout 的 take 会返回错误
 * @Given 在中断上下文中（g_interrupt_nest > 0）
 * @When 以 timeout > 0 调用 mrtk_sem_take()
 * @Then 返回 MRTK_ERROR
 */
TEST_F(MrtkSemTest, Sem_Take_InInterruptContext_WithTimeout_ReturnsError) {
    // Step 1: Given - 模拟中断上下文
    set_interrupt_nest(1);
    mrtk_sem_init(&test_sem_static, "TestSem", 0,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 在中断中尝试阻塞获取
    mrtk_err_t ret = mrtk_sem_take(&test_sem_static, 100);

    // Step 3: Then - 验证返回错误
    EXPECT_EQ(ret, MRTK_E_IN_ISR);

    // 恢复中断嵌套
    set_interrupt_nest(0);
}

/**
 * @test Sem_Take_InInterruptContext_ZeroTimeout_Succeeds
 * @brief 测试中断上下文中非阻塞获取
 * @details 验证在中断中以 timeout=0 获取可以成功
 * @Given 在中断上下文中且信号量有资源
 * @When 以 timeout=0 调用 mrtk_sem_take()
 * @Then 返回 MRTK_EOK
 */
TEST_F(MrtkSemTest, Sem_Take_InInterruptContext_ZeroTimeout_Succeeds) {
    // Step 1: Given - 模拟中断上下文且有资源
    set_interrupt_nest(1);
    mrtk_sem_init(&test_sem_static, "TestSem", 1,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 在中断中尝试非阻塞获取
    mrtk_err_t ret = mrtk_sem_take(&test_sem_static, 0);

    // Step 3: Then - 验证成功获取
    EXPECT_EQ(ret, MRTK_EOK);
    verify_sem_value(&test_sem_static, 0);

    // 恢复中断嵌套
    set_interrupt_nest(0);
}

/**
 * @test Sem_Take_ResourceExhausted_TasksBlockOnWaitQueue
 * @brief 测试资源耗尽时多任务阻塞
 * @details 验证多个任务在等待队列中阻塞
 * @Given 信号量无资源，多个任务尝试获取
 * @When 各任务调用 mrtk_sem_take() 阻塞
 * @Then 任务被挂起到等待队列
 */
TEST_F(MrtkSemTest, Sem_Take_ResourceExhausted_TasksBlockOnWaitQueue) {
    // Step 1: Given - 信号量无资源
    mrtk_sem_init(&test_sem_static, "TestSem", 0,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 尝试获取（将阻塞）
    // 注意：实际阻塞需要模拟调度器行为
    mrtk_err_t ret = mrtk_sem_take(&test_sem_static, 100);

    // Step 3: Then - 验证任务被挂起
    // 在真实执行中，任务会被挂起到等待队列
}

/**
 * @test Sem_Take_Null_ReturnsError
 * @brief 测试获取 MRTK_NULL 信号量（防御性测试）
 * @Given MRTK_NULL 信号量指针
 * @When 调用 mrtk_sem_take()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkSemTest, Sem_Take_Null_ReturnsError) {
    // Step 1: Given - MRTK_NULL 信号量指针
    set_current_task(&task_high);

    // Step 2: When - 执行获取
    mrtk_err_t ret = mrtk_sem_take(nullptr, 100);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_sem_trytake() 测试用例
 * ============================================================================== */

/**
 * @test Sem_Trytake_AvailableResource_Success
 * @brief 测试非阻塞获取有资源的信号量
 * @details 验证 trytake 在资源可用时能成功获取
 * @Given 有可用资源的信号量
 * @When 调用 mrtk_sem_trytake()
 * @Then 返回 MRTK_EOK，资源计数减 1
 */
TEST_F(MrtkSemTest, Sem_Trytake_AvailableResource_Success) {
    // Step 1: Given - 有资源的信号量
    mrtk_sem_init(&test_sem_static, "TestSem", 3,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 尝试非阻塞获取
    mrtk_err_t ret = mrtk_sem_trytake(&test_sem_static);

    // Step 3: Then - 验证成功获取
    EXPECT_EQ(ret, MRTK_EOK);
    verify_sem_value(&test_sem_static, 2);
}

/**
 * @test Sem_Trytake_NoResource_ImmediateFailure
 * @brief 测试非阻塞获取无资源的信号量
 * @details 验证 trytake 在资源不足时立即返回错误
 * @Given 无可用资源的信号量
 * @When 调用 mrtk_sem_trytake()
 * @Then 返回 MRTK_ERROR
 */
TEST_F(MrtkSemTest, Sem_Trytake_NoResource_ImmediateFailure) {
    // Step 1: Given - 无资源的信号量
    mrtk_sem_init(&test_sem_static, "TestSem", 0,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 尝试非阻塞获取
    mrtk_err_t ret = mrtk_sem_trytake(&test_sem_static);

    // Step 3: Then - 验证立即返回错误
    EXPECT_EQ(ret, MRTK_ERROR);
    verify_sem_value(&test_sem_static, 0);
}

/**
 * @test Sem_Trytake_Null_ReturnsError
 * @brief 测试 trytake MRTK_NULL 信号量（防御性测试）
 * @Given MRTK_NULL 信号量指针
 * @When 调用 mrtk_sem_trytake()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkSemTest, Sem_Trytake_Null_ReturnsError) {
    // Step 1: Given - MRTK_NULL 信号量指针
    set_current_task(&task_high);

    // Step 2: When - 执行 trytake
    mrtk_err_t ret = mrtk_sem_trytake(nullptr);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_sem_release() 测试用例
 * ============================================================================== */

/**
 * @test Sem_Release_NoWaitingTasks_IncrementValue
 * @brief 测试释放信号量时无等待任务
 * @details 验证无等待任务时资源计数加 1
 * @Given 信号量无等待任务
 * @When 调用 mrtk_sem_release()
 * @Then 返回 MRTK_EOK，资源计数加 1
 */
TEST_F(MrtkSemTest, Sem_Release_NoWaitingTasks_IncrementValue) {
    // Step 1: Given - 初始化信号量为 0
    mrtk_sem_init(&test_sem_static, "TestSem", 0,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 释放信号量
    mrtk_err_t ret = mrtk_sem_release(&test_sem_static);

    // Step 3: Then - 验证资源计数加 1
    EXPECT_EQ(ret, MRTK_EOK);
    verify_sem_value(&test_sem_static, 1);
}

/**
 * @test Sem_Release_ValueOverflow_BoundaryTest
 * @brief 测试信号量值回卷（边界值）
 * @details 验证 UINT16_MAX + 1 回卷为 0
 * @Given 信号量值为 UINT16_MAX
 * @When 调用 mrtk_sem_release()
 * @Then 返回 MRTK_EFULL 4（无符号溢出）
 */
TEST_F(MrtkSemTest, Sem_Release_ValueOverflow_BoundaryTest) {
    // Step 1: Given - 信号量值为最大值
    mrtk_sem_init(&test_sem_static, "TestSem", UINT16_MAX,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 释放信号量（触发回卷）
    mrtk_err_t ret = mrtk_sem_release(&test_sem_static);

    // Step 3: Then - 验证回卷到 0
    EXPECT_EQ(ret, MRTK_EFULL);
}

/**
 * @test Sem_Release_WithWaitingTasks_WakeupOneTask
 * @brief 测试释放时有等待任务的情况
 * @details 验证释放时唤醒一个等待任务，资源计数不变
 * @Given 信号量有任务在等待队列中
 * @When 调用 mrtk_sem_release()
 * @Then 等待队列中的一个任务被唤醒，资源计数不变（直接移交）
 */
TEST_F(MrtkSemTest, Sem_Release_WithWaitingTasks_WakeupOneTask) {
    // Step 1: Given - 信号量无资源，有任务等待
    mrtk_sem_init(&test_sem_static, "TestSem", 0,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // 将高优先级任务挂起到等待队列
    make_task_suspend(&task_high);
    task_high.last_error = MRTK_EOK;
    _mrtk_list_insert_before(&test_sem_static.ipc_obj.suspend_taker,
                          &task_high.sched_node);

    // Step 2: When - 释放信号量
    mrtk_err_t ret = mrtk_sem_release(&test_sem_static);

    // Step 3: Then - 验证高优先级任务被唤醒，资源计数不变
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(task_high.state, MRTK_TASK_STAT_READY); /* 被唤醒 */
    verify_sem_value(&test_sem_static, 0); /* 直接移交，不变 */
}

/**
 * @test Sem_Release_MultipleWaitingTasks_WakeupHighestPriority
 * @brief 测试 PRIO 策略下唤醒最高优先级任务
 * @details 验证按优先级唤醒机制
 * @Given PRIO 策略信号量，多个任务在等待队列
 * @When 调用 mrtk_sem_release()
 * @Then 最高优先级任务被唤醒
 */
/**
 * @test Sem_Release_MultipleWaitingTasks_WakeupHighestPriority
 * @brief 测试 PRIO 策略下优先级最高的任务被唤醒
 * @details Given PRIO 策略信号量，多个任务在等待队列
 *          When 调用 mrtk_sem_release()
 *          Then 优先级最高的任务被唤醒
 * @note 使用 _mrtk_ipc_suspend_one 模拟任务阻塞，避免依赖任务调度器
 */
TEST_F(MrtkSemTest, Sem_Release_MultipleWaitingTasks_WakeupHighestPriority) {
    // Step 1: Given - PRIO 策略信号量，多个任务等待
    mrtk_sem_init(&test_sem_static, "TestSem", 0,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    /*
     * 模拟 PRIO 策略下的任务阻塞场景：
     * - _mrtk_ipc_suspend_one() 会根据 flag 参数（FIFO/PRIO）决定插入位置
     * - PRIO 策略会按优先级从高到低排序等待队列
     * - 无论插入顺序如何，最终链表都是 [high, mid, low]
     */
    make_task_suspend(&task_mid);
    _mrtk_ipc_suspend_one(&test_sem_static.ipc_obj.suspend_taker,
                          test_sem_static.ipc_obj.flag, &task_mid);

    make_task_suspend(&task_low);
    _mrtk_ipc_suspend_one(&test_sem_static.ipc_obj.suspend_taker,
                          test_sem_static.ipc_obj.flag, &task_low);

    make_task_suspend(&task_high);
    _mrtk_ipc_suspend_one(&test_sem_static.ipc_obj.suspend_taker,
                          test_sem_static.ipc_obj.flag, &task_high);

    // Step 2: When - 释放信号量
    mrtk_err_t ret = mrtk_sem_release(&test_sem_static);

    // Step 3: Then - 验证最高优先级任务被唤醒
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(task_high.state, MRTK_TASK_STAT_READY);
}

/**
 * @test Sem_Release_FIFO_WaitingOrder_FIFOWakeup
 * @brief 测试 FIFO 策略下的唤醒顺序
 * @details 验证 FIFO 策略按等待顺序唤醒
 * @Given FIFO 策略信号量，多个任务在等待队列
 * @When 调用 mrtk_sem_release()
 * @Then 按照等待顺序（先来先得）唤醒任务
 */
TEST_F(MrtkSemTest, Sem_Release_FIFO_WaitingOrder_FIFOWakeup) {
    // Step 1: Given - FIFO 策略信号量，多个任务按顺序等待
    mrtk_sem_init(&test_sem_static, "TestSem", 0,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_FIFO);

    // 按顺序插入任务
    make_task_suspend(&task_high);
    _mrtk_list_insert_before(&test_sem_static.ipc_obj.suspend_taker,
                          &task_high.sched_node);

    make_task_suspend(&task_mid);
    _mrtk_list_insert_before(&test_sem_static.ipc_obj.suspend_taker,
                          &task_mid.sched_node);

    make_task_suspend(&task_low);
    _mrtk_list_insert_before(&test_sem_static.ipc_obj.suspend_taker,
                          &task_low.sched_node);

    // Step 2: When - 释放信号量
    mrtk_err_t ret = mrtk_sem_release(&test_sem_static);

    // Step 3: Then - 验证第一个等待者（高优先级任务）被唤醒
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(task_high.state, MRTK_TASK_STAT_READY);
}

/**
 * @test Sem_Release_Null_ReturnsError
 * @brief 测试释放 MRTK_NULL 信号量（防御性测试）
 * @Given MRTK_NULL 信号量指针
 * @When 调用 mrtk_sem_release()
 * @then 触发 MRTK_ASSERT
 */
TEST_F(MrtkSemTest, Sem_Release_Null_ReturnsError) {
    // Step 1: Given - MRTK_NULL 信号量指针
    // Step 2: When - 执行释放
    mrtk_err_t ret = mrtk_sem_release(nullptr);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_sem_control() 测试用例
 * ============================================================================== */

/**
 * @test Sem_Control_GetValue_ValidSem_ReturnsCorrectValue
 * @brief 测试 GET_VALUE 命令 - 正常获取信号量值
 * @details 验证 control 接口能正确查询信号量当前计数值
 * @Given 初始化信号量（初始值为 5）
 * @When 调用 mrtk_sem_control() 使用 GET_VALUE 命令
 * @then 返回 MRTK_EOK，且 arg 指向的值为 5
 */
TEST_F(MrtkSemTest, Sem_Control_GetValue_ValidSem_ReturnsCorrectValue) {
    // Step 1: Given - 初始化信号量（初始值为 5）
    mrtk_u16_t init_value = 5;
    mrtk_sem_init(&test_sem_static, "TestSem", init_value,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 调用 control 查询当前值
    mrtk_u16_t  value = 0;
    mrtk_err_t  ret   = mrtk_sem_control(&test_sem_static, MRTK_SEM_CMD_GET_VALUE, &value);

    // Step 3: Then - 验证返回值和查询结果
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(value, init_value);
}

/**
 * @test Sem_Control_GetValue_AfterTake_DecreasesValue
 * @brief 测试 GET_VALUE 命令 - take 后值减少
 * @details 验证信号量 take 操作后，查询值正确减少
 * @Given 初始化信号量（初始值为 3），执行一次 take
 * @When 调用 mrtk_sem_control() 使用 GET_VALUE 命令
 * @then 返回 MRTK_EOK，且查询值为 2
 */
TEST_F(MrtkSemTest, Sem_Control_GetValue_AfterTake_DecreasesValue) {
    // Step 1: Given - 初始化信号量并执行一次 take
    mrtk_u16_t init_value = 3;
    mrtk_sem_init(&test_sem_static, "TestSem", init_value,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_err_t ret = mrtk_sem_take(&test_sem_static, 0);
    EXPECT_EQ(ret, MRTK_EOK);

    // Step 2: When - 查询当前值
    mrtk_u16_t value = 0;
    ret = mrtk_sem_control(&test_sem_static, MRTK_SEM_CMD_GET_VALUE, &value);

    // Step 3: Then - 验证值减少 1
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(value, init_value - 1);
}

/**
 * @test Sem_Control_GetValue_AfterRelease_IncreasesValue
 * @brief 测试 GET_VALUE 命令 - release 后值增加
 * @details 验证信号量 release 操作后，查询值正确增加
 * @Given 初始化信号量（初始值为 2），执行一次 release
 * @When 调用 mrtk_sem_control() 使用 GET_VALUE 命令
 * @then 返回 MRTK_EOK，且查询值为 3
 */
TEST_F(MrtkSemTest, Sem_Control_GetValue_AfterRelease_IncreasesValue) {
    // Step 1: Given - 初始化信号量并执行一次 release
    mrtk_u16_t init_value = 2;
    mrtk_sem_init(&test_sem_static, "TestSem", init_value,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_err_t ret = mrtk_sem_release(&test_sem_static);
    EXPECT_EQ(ret, MRTK_EOK);

    // Step 2: When - 查询当前值
    mrtk_u16_t value = 0;
    ret = mrtk_sem_control(&test_sem_static, MRTK_SEM_CMD_GET_VALUE, &value);

    // Step 3: Then - 验证值增加 1
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(value, init_value + 1);
}

/**
 * @test Sem_Control_GetValue_NullSem_ReturnsError
 * @brief 测试 GET_VALUE 命令 - 空信号量指针
 * @details 验证传入空指针时，control 返回错误
 * @Given 信号量对象为 nullptr
 * @When 调用 mrtk_sem_control() 使用 GET_VALUE 命令
 * @then 返回 MRTK_EINVAL
 */
TEST_F(MrtkSemTest, Sem_Control_GetValue_NullSem_ReturnsError) {
    // Step 1: Given - 空信号量指针
    mrtk_u16_t value = 0;

    // Step 2: When - 调用 control 传入空指针
    mrtk_err_t ret = mrtk_sem_control(nullptr, MRTK_SEM_CMD_GET_VALUE, &value);

    // Step 3: Then - 预期返回参数错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test Sem_Control_GetValue_NullArg_ReturnsError
 * @brief 测试 GET_VALUE 命令 - 空 arg 指针
 * @details 验证传入空 arg 指针时，control 返回错误
 * @Given 初始化信号量，arg 为 nullptr
 * @When 调用 mrtk_sem_control() 使用 GET_VALUE 命令
 * @then 返回 MRTK_EINVAL
 */
TEST_F(MrtkSemTest, Sem_Control_GetValue_NullArg_ReturnsError) {
    // Step 1: Given - 初始化信号量
    mrtk_sem_init(&test_sem_static, "TestSem", 1,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 调用 control 传入空 arg
    mrtk_err_t ret = mrtk_sem_control(&test_sem_static, MRTK_SEM_CMD_GET_VALUE, nullptr);

    // Step 3: Then - 预期返回参数错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test Sem_Control_UnknownCommand_ReturnsError
 * @brief 测试未知命令
 * @details 验证传入未实现的命令时，control 返回错误
 * @Given 初始化信号量
 * @When 调用 mrtk_sem_control() 使用未知命令
 * @then 返回 MRTK_ERROR
 */
TEST_F(MrtkSemTest, Sem_Control_UnknownCommand_ReturnsError) {
    // Step 1: Given - 初始化信号量
    mrtk_sem_init(&test_sem_static, "TestSem", 1,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    mrtk_u16_t value = 0;

    // Step 2: When - 调用 control 使用未知命令
    mrtk_err_t ret = mrtk_sem_control(&test_sem_static, 0xFF, &value);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_ERROR);
}

/**
 * @test Sem_Control_GetValue_ZeroSemaphore
 * @brief 测试 GET_VALUE 命令 - 零值信号量
 * @details 验证零值信号量（二值信号量初始状态）查询正确
 * @Given 初始化信号量（初始值为 0）
 * @When 调用 mrtk_sem_control() 使用 GET_VALUE 命令
 * @then 返回 MRTK_EOK，且查询值为 0
 */
TEST_F(MrtkSemTest, Sem_Control_GetValue_ZeroSemaphore) {
    // Step 1: Given - 初始化零值信号量
    mrtk_sem_init(&test_sem_static, "ZeroSem", 0, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 查询当前值
    mrtk_u16_t value = 0;
    mrtk_err_t ret =
        mrtk_sem_control(&test_sem_static, MRTK_SEM_CMD_GET_VALUE, &value);

    // Step 3: Then - 验证值为 0
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(value, 0);
}

/**
 * @test Sem_Control_GetValue_MaxValueSemaphore
 * @brief 测试 GET_VALUE 命令 - 最大值信号量
 * @details 验证最大值信号量（计数信号量满载）查询正确
 * @Given 初始化信号量（初始值为 MRTK_SEM_MAX_VALUE）
 * @When 调用 mrtk_sem_control() 使用 GET_VALUE 命令
 * @then 返回 MRTK_EOK，且查询值为 MRTK_SEM_MAX_VALUE
 */
TEST_F(MrtkSemTest, Sem_Control_GetValue_MaxValueSemaphore) {
    // Step 1: Given - 初始化最大值信号量
    mrtk_sem_init(&test_sem_static, "MaxSem", MRTK_SEM_MAX_VALUE,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 查询当前值
    mrtk_u16_t value = 0;
    mrtk_err_t ret =
        mrtk_sem_control(&test_sem_static, MRTK_SEM_CMD_GET_VALUE, &value);

    // Step 3: Then - 验证值为最大值
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(value, MRTK_SEM_MAX_VALUE);
}

/* ==============================================================================
 * 综合场景测试
 * ============================================================================== */

/**
 * @test Sem_BinarySemaphore_ProducerConsumer
 * @brief 测试二值信号量用于生产者-消费者同步
 * @details 验证信号量作为同步原语（value = 0/1）
 * @Given 二值信号量（初始值 0）
 * @When 生产者 release，消费者 take
 * @then 同步正常工作
 */
TEST_F(MrtkSemTest, Sem_BinarySemaphore_ProducerConsumer) {
    // Step 1: Given - 二值信号量（初始值 0）
    mrtk_sem_init(&test_sem_static, "BinarySem", 0,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 生产者释放（从 0 到 1）
    mrtk_err_t ret_release = mrtk_sem_release(&test_sem_static);
    ASSERT_EQ(ret_release, MRTK_EOK);
    verify_sem_value(&test_sem_static, 1);

    // 消费者获取（从 1 到 0）
    mrtk_err_t ret_take = mrtk_sem_take(&test_sem_static, 0);

    // Step 3: Then - 验证同步成功
    EXPECT_EQ(ret_take, MRTK_EOK);
    verify_sem_value(&test_sem_static, 0);
}

/**
 * @test Sem_CountingSemaphore_ResourcePool
 * @brief 测试计数信号量用于资源池管理
 * @details 验证多个资源的获取和释放
 * @Given 计数信号量（初始值 = 资源数量）
 * @When 多次 take 和 release
 * @then 资源计数正确维护
 */
TEST_F(MrtkSemTest, Sem_CountingSemaphore_ResourcePool) {
    // Step 1: Given - 计数信号量（资源池大小为 5）
    mrtk_u16_t pool_size = 5;
    mrtk_sem_init(&test_sem_static, "ResourcePool", pool_size,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 获取 3 个资源
    for (mrtk_u16_t i = 0; i < 3; ++i) {
        mrtk_err_t ret = mrtk_sem_take(&test_sem_static, 0);
        ASSERT_EQ(ret, MRTK_EOK);
    }
    verify_sem_value(&test_sem_static, 2); /* 5 - 3 = 2 */

    // 释放 1 个资源
    mrtk_err_t ret_release = mrtk_sem_release(&test_sem_static);
    ASSERT_EQ(ret_release, MRTK_EOK);

    // Step 3: Then - 验证资源计数正确
    verify_sem_value(&test_sem_static, 3); /* 2 + 1 = 3 */
}

/**
 * @test Sem_CompleteLifecycle_InitTakeReleaseDetach_Success
 * @brief 测试信号量完整生命周期
 * @details 验证 Init → Take → Release → Detach 的完整流程
 * @Given 信号量对象
 * @When 依次执行 init, take, release, detach
 * @Then 每一步都成功返回
 */
TEST_F(MrtkSemTest, Sem_CompleteLifecycle_InitTakeReleaseDetach_Success) {
    // Step 1: Given - 信号量对象和任务

    // Step 2: When - 执行完整生命周期
    mrtk_err_t ret_init = mrtk_sem_init(&test_sem_static, "LifecycleSem", 1,
                                         MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_err_t ret_take = mrtk_sem_take(&test_sem_static, 100);
    mrtk_err_t ret_release = mrtk_sem_release(&test_sem_static);
    mrtk_err_t ret_detach = mrtk_sem_detach(&test_sem_static);

    // Step 3: Then - 验证每一步都成功
    EXPECT_EQ(ret_init, MRTK_EOK);
    EXPECT_EQ(ret_take, MRTK_EOK);
    EXPECT_EQ(ret_release, MRTK_EOK);
    EXPECT_EQ(ret_detach, MRTK_EOK);
}

/**
 * @test Sem_ResourceExhaustion_AllResourcesTaken
 * @brief 测试资源耗尽场景
 * @details 验证所有资源都被获取后，再获取会阻塞
 * @Given 信号量有 N 个资源
 * @When 获取 N+1 次
 * @Then 第 N+1 次获取会失败或阻塞
 */
TEST_F(MrtkSemTest, Sem_ResourceExhaustion_AllResourcesTaken) {
    // Step 1: Given - 信号量有 2 个资源
    mrtk_u16_t pool_size = 2;
    mrtk_sem_init(&test_sem_static, "ResourcePool", pool_size,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 获取所有资源
    mrtk_err_t ret1 = mrtk_sem_take(&test_sem_static, 0);
    mrtk_err_t ret2 = mrtk_sem_take(&test_sem_static, 0);

    // 第 3 次获取应失败（非阻塞模式）
    mrtk_err_t ret3 = mrtk_sem_take(&test_sem_static, 0);

    // Step 3: Then - 验证前两次成功，第三次失败
    EXPECT_EQ(ret1, MRTK_EOK);
    EXPECT_EQ(ret2, MRTK_EOK);
    EXPECT_EQ(ret3, MRTK_ERROR);
    verify_sem_value(&test_sem_static, 0);
}

/**
 * @test Sem_InterruptContext_NonBlockingOperations_Only
 * @brief 测试中断上下文中的信号量操作限制
 * @details 验证中断中只能进行非阻塞操作
 * @Given 在中断上下文中
 * @When 尝试阻塞操作 vs 非阻塞操作
 * @Then 阻塞操作返回错误，非阻塞操作成功
 */
TEST_F(MrtkSemTest, Sem_InterruptContext_NonBlockingOperations_Only) {
    // Step 1: Given - 中断上下文
    set_interrupt_nest(1);
    mrtk_sem_init(&test_sem_static, "TestSem", 1,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 在中断中尝试各种操作
    mrtk_err_t ret_nonblock = mrtk_sem_take(&test_sem_static, 0); /* 允许 */
    mrtk_err_t ret_block    = mrtk_sem_take(&test_sem_static, 100); /* 禁止 */
    mrtk_err_t ret_release  = mrtk_sem_release(&test_sem_static); /* 允许 */

    // Step 3: Then - 验证结果
    EXPECT_EQ(ret_nonblock, MRTK_EOK);
    EXPECT_EQ(ret_block, MRTK_E_IN_ISR);
    EXPECT_EQ(ret_release, MRTK_EOK);

    // 恢复中断嵌套
    set_interrupt_nest(0);
}

/**
 * @test Sem_ConcurrentAccess_MultipleTasks
 * @brief 测试多任务并发访问信号量
 * @details 验证信号量在多任务环境下的正确性
 * @Given 多个任务同时访问信号量
 * @When 各任务进行 take/release 操作
 * @Then 资源计数正确，无竞态条件
 */
TEST_F(MrtkSemTest, Sem_ConcurrentAccess_MultipleTasks) {
    // Step 1: Given - 初始化信号量，资源计数为 2
    mrtk_sem_init(&test_sem_static, "ConcurrentSem", 2,
                  MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 模拟多任务访问
    // 高优先级任务获取资源
    set_current_task(&task_high);
    make_task_ready(&task_high);
    mrtk_err_t ret1 = mrtk_sem_take(&test_sem_static, 0);
    ASSERT_EQ(ret1, MRTK_EOK);

    // 中优先级任务获取资源
    set_current_task(&task_mid);
    make_task_ready(&task_mid);
    mrtk_err_t ret2 = mrtk_sem_take(&test_sem_static, 0);
    ASSERT_EQ(ret2, MRTK_EOK);

    // 低优先级任务尝试获取（应失败）
    set_current_task(&task_low);
    make_task_ready(&task_low);
    mrtk_err_t ret3 = mrtk_sem_take(&test_sem_static, 0);

    // Step 3: Then - 验证资源耗尽
    EXPECT_EQ(ret3, MRTK_ERROR);
    verify_sem_value(&test_sem_static, 0);
}

#endif /* (MRTK_USING_SEMAPHORE == 1) */
