/**
 * @file mrtk_mail_box_test.cpp
 * @author leiyx (Generated by SDET Architecture)
 * @brief 邮箱模块单元测试套件
 * @details 严格遵循 BDD 风格（Given-When-Then），覆盖边界值、等价类、分支覆盖和状态机
 *
 * 测试覆盖策略：
 * 1. 边界值分析：size=1/MAX、timeout=0/MRTK_WAIT_FOREVER、环形缓冲区回绕、满/空边界
 * 2. 等价类划分：NULL参数、静态/动态对象、FIFO/PRIO策略、各种错误码
 * 3. 分支覆盖：while循环条件、满/空邮箱、阻塞/非阻塞分支、双向唤醒链表
 * 4. 状态机覆盖：INIT → SEND/RECV → FULL/EMPTY → DETACH/DELETE 全生命周期
 * 5. 并发场景：多发送者/接收者、虚假唤醒处理、环形缓冲区回绕
 * @copyright Copyright (c) 2026
 */

#include <gtest/gtest.h>
#include <gmock/gmock.h>

/* Mock 头文件（C++ 代码，必须在最前） */
#include "mrtk_mock_hw.hpp"

#if (MRTK_USING_MAILBOX == 1)

/* MRTK 头文件（已包含 extern "C"） */
#include "mrtk.h"

/* ==============================================================================
 * 测试夹具：MrtkMailBoxTest
 * ============================================================================== */

/**
 * @class MrtkMailBoxTest
 * @brief 邮箱模块测试夹具
 * @details 提供 Mock 环境、系统初始化和辅助方法
 */
class MrtkMailBoxTest : public ::testing::Test {
  protected:
    /* Mock 对象（使用 NiceMock 自动忽略未设置期望的调用，避免 GMOCK WARNING） */
    testing::NiceMock<MockCpuPort> mock_cpu_port;

    /* 测试用邮箱对象 */
    mrtk_mb_t test_mb_static;
    mrtk_mb_t *test_mb_dynamic = nullptr;

    /* 测试用邮箱池（静态分配） */
    static constexpr mrtk_u32_t MAILBOX_SIZE = 256; /* 字节 */
    mrtk_u32_t mb_pool_buffer[64]; /* 256 字节，足够存储 64 个 mrtk_u32_t */
    mrtk_u32_t mb_pool_small[4];   /* 小邮箱池，用于边界测试 */

    /* 测试用任务对象 */
    static constexpr mrtk_u32_t TASK_STACK_SIZE = 512;
    mrtk_u32_t task_stack_high[512];
    mrtk_u32_t task_stack_mid[512];
    mrtk_u32_t task_stack_low[512];
    mrtk_task_t task_high;
    mrtk_task_t task_mid;
    mrtk_task_t task_low;

    /* 优先级定义 */
    static constexpr mrtk_u8_t PRIO_HIGH = 5;
    static constexpr mrtk_u8_t PRIO_MID  = 10;
    static constexpr mrtk_u8_t PRIO_LOW  = 20;

    /* 任务入口函数（空实现，仅用于测试） */
    static mrtk_void_t dummy_task_entry(mrtk_void_t *param) {
        (void)param;
        /* 测试任务不会实际运行，仅验证状态管理 */
    }

  protected:
    /**
     * @brief 测试环境初始化
     * @details 执行顺序：系统初始化 → 设置 Mock → 设置默认行为 → 初始化测试对象
     */
    void SetUp() override {
        /* Step 1: 系统初始化（复位全局变量） */
        mrtk_system_init();

        g_CurrentTCB = mrtk_task_get_idle();

        /* Step 2: 设置 Mock 对象 */
        mrtk_mock_set_cpu_port(&mock_cpu_port);

        /* Step 3: 设置默认期望行为（避免对中断控制产生不必要依赖） */
        ON_CALL(mock_cpu_port, mrtk_hw_interrupt_disable)
            .WillByDefault(testing::Return(0));
        ON_CALL(mock_cpu_port, mrtk_hw_interrupt_enable)
            .WillByDefault(testing::Return());
        ON_CALL(mock_cpu_port, mrtk_hw_context_switch_interrupt)
            .WillByDefault(testing::Return());

        /* Step 4: 初始化测试任务 */
        init_test_tasks();
    }

    /**
     * @brief 测试环境清理
     * @details 清除 Mock 对象，释放动态分配的资源
     */
    void TearDown() override {
        /* 释放动态创建的邮箱 */
        if (test_mb_dynamic != nullptr) {
            mrtk_free(test_mb_dynamic);
            test_mb_dynamic = nullptr;
        }

        /* 清除 Mock 对象 */
        mrtk_mock_clear_cpu_port();
    }

    /**
     * @brief 初始化测试用任务
     * @details 创建高/中/低三个优先级的任务，用于测试多任务场景
     */
    void init_test_tasks(mrtk_void_t) {
        mrtk_task_init("TaskHigh", &task_high, dummy_task_entry, nullptr,
                       task_stack_high, TASK_STACK_SIZE, PRIO_HIGH, 10);
        mrtk_task_init("TaskMid", &task_mid, dummy_task_entry, nullptr,
                       task_stack_mid, TASK_STACK_SIZE, PRIO_MID, 10);
        mrtk_task_init("TaskLow", &task_low, dummy_task_entry, nullptr,
                       task_stack_low, TASK_STACK_SIZE, PRIO_LOW, 10);
    }

    /**
     * @brief 设置当前运行任务
     * @details 模拟指定任务正在运行，用于测试邮箱操作
     * @param[in] task 要设置为当前运行的任务指针
     */
    void set_current_task(mrtk_task_t *task) {
        extern mrtk_tcb_t *volatile g_CurrentTCB;
        g_CurrentTCB = task;
    }

    /**
     * @brief 验证邮箱状态
     * @details 断言邮箱的关键字段是否符合预期
     * @param[in] mb          邮箱指针
     * @param[in] cur_cnt     期望的当前邮件数量
     * @param[in] in_offset   期望的写入偏移量
     * @param[in] out_offset  期望的读取偏移量
     */
    void verify_mb_state(mrtk_mb_t *mb, mrtk_u16_t cur_cnt, mrtk_u16_t in_offset,
                         mrtk_u16_t out_offset) {
        EXPECT_EQ(mb->cur_mail_cnt, cur_cnt);
        EXPECT_EQ(mb->in_offset, in_offset);
        EXPECT_EQ(mb->out_offset, out_offset);
    }

    /**
     * @brief 设置任务为就绪状态
     * @details 将任务插入对应优先级的就绪队列
     * @param[in] task 要设置为就绪的任务
     */
    void make_task_ready(mrtk_task_t *task) {
        task->state = MRTK_TASK_STAT_READY;
        _mrtk_schedule_insert_task(task);
    }

    /**
     * @brief 设置任务为挂起状态
     * @details 将任务从就绪队列移除并标记为挂起
     * @param[in] task 要设置为挂起的任务
     */
    void make_task_suspend(mrtk_task_t *task) {
        _mrtk_schedule_remove_task(task);
        task->state = MRTK_TASK_STAT_SUSPEND;
    }
};

/* ==============================================================================
 * mrtk_mb_init() 测试用例
 * ============================================================================== */

/**
 * @test MB_Init_ValidParameters_Success
 * @brief 测试正常初始化邮箱
 * @details 验证邮箱初始化后所有字段是否正确设置
 * @Given 有效的邮箱指针、邮箱池和参数
 * @When 调用 mrtk_mb_init()
 * @Then 返回 MRTK_EOK，邮箱状态正确
 */
TEST_F(MrtkMailBoxTest, MB_Init_ValidParameters_Success) {
    // Step 1: Given - 准备有效的邮箱对象和参数
    const mrtk_char_t *mb_name = "TestMB";
    mrtk_u8_t flag = MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO;

    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_mb_init(&test_mb_static, mb_pool_buffer, MAILBOX_SIZE, (mrtk_char_t *)mb_name, flag);

    // Step 3: Then - 验证返回值和邮箱状态
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mb_static.msg_pool, mb_pool_buffer);
    EXPECT_GT(test_mb_static.max_mail_cnt, 0);
    verify_mb_state(&test_mb_static, 0, 0, 0);
}

/**
 * @test MB_Init_SmallSize_Success
 * @brief 测试小容量邮箱初始化（边界值）
 * @details 验证最小邮箱容量（对齐后仅能容纳 1 封邮件）
 * @Given 邮箱池大小仅能容纳 1 封邮件
 * @When 调用 mrtk_mb_init()
 * @Then 返回 MRTK_EOK，max_mail_cnt = 1
 */
TEST_F(MrtkMailBoxTest, MB_Init_SmallSize_Success) {
    // Step 1: Given - 小邮箱池（4 字节，仅能容纳 1 个 mrtk_u32_t）
    const mrtk_char_t *mb_name = "SmallMB";

    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_mb_init(&test_mb_static, mb_pool_small, sizeof(mrtk_u32_t), (mrtk_char_t *)mb_name,
                                   MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 验证成功且容量为 1
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mb_static.max_mail_cnt, 1);
}

/**
 * @test MB_Init_NullMb_ReturnsError
 * @brief 测试 MRTK_NULL 邮箱指针（防御性测试）
 * @Given MRTK_NULL 邮箱指针
 * @When 调用 mrtk_mb_init()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMailBoxTest, MB_Init_NullMb_ReturnsError) {
    // Step 1: Given - MRTK_NULL 邮箱指针
    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_mb_init(nullptr, mb_pool_buffer, MAILBOX_SIZE, "TestMB",
                                   MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test MB_Init_NullMsgPool_ReturnsError
 * @brief 测试 MRTK_NULL 邮箱池指针（防御性测试）
 * @Given MRTK_NULL 邮箱池指针
 * @When 调用 mrtk_mb_init()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMailBoxTest, MB_Init_NullMsgPool_ReturnsError) {
    // Step 1: Given - MRTK_NULL 邮箱池指针
    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_mb_init(&test_mb_static, nullptr, MAILBOX_SIZE, "TestMB",
                                   MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test MB_Init_NullName_ReturnsError
 * @brief 测试 MRTK_NULL 名称参数（防御性测试）
 * @Given MRTK_NULL 名称参数
 * @When 调用 mrtk_mb_init()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMailBoxTest, MB_Init_NullName_ReturnsError) {
    // Step 1: Given - MRTK_NULL 名称参数
    // Step 2: When - 执行初始化
    mrtk_err_t ret = mrtk_mb_init(&test_mb_static, mb_pool_buffer, MAILBOX_SIZE, nullptr,
                                   MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_mb_detach() 测试用例
 * ============================================================================== */

/**
 * @test MB_Detach_ValidMB_Success
 * @brief 测试正常脱离邮箱
 * @details 验证脱离静态邮箱后的状态
 * @Given 已初始化的静态邮箱
 * @When 调用 mrtk_mb_detach()
 * @Then 返回 MRTK_EOK，所有等待发送者被唤醒
 */
TEST_F(MrtkMailBoxTest, MB_Detach_ValidMB_Success) {
    // Step 1: Given - 初始化邮箱
    mrtk_mb_init(&test_mb_static, mb_pool_buffer, MAILBOX_SIZE, "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 脱离邮箱
    mrtk_err_t ret = mrtk_mb_detach(&test_mb_static);

    // Step 3: Then - 验证返回值
    EXPECT_EQ(ret, MRTK_EOK);
}

/**
 * @test MB_Detach_WithWaitingSenders_SendersResumedWithError
 * @brief 测试脱离时有等待发送者的邮箱
 * @details 验证脱离时唤醒所有等待发送者并设置错误码
 * @Given 邮箱已满，有任务在等待发送队列中
 * @When 调用 mrtk_mb_detach()
 * @Then 所有等待发送者被唤醒，last_error 设置为 MRTK_EDELETED
 */
TEST_F(MrtkMailBoxTest, MB_Detach_WithWaitingSenders_SendersResumedWithError) {
    // Step 1: Given - 初始化邮箱并有任务等待发送
    mrtk_mb_init(&test_mb_static, mb_pool_small, sizeof(mrtk_u32_t), "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // 填满邮箱
    mrtk_u32_t mail = 0x12345678;
    mrtk_mb_send_wait(&test_mb_static, &mail, 0);
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 1);

    // 将高优先级任务挂起到发送者等待队列
    set_current_task(&task_high);
    make_task_suspend(&task_high);
    task_high.last_error = MRTK_EOK;
    _mrtk_list_insert_before(&test_mb_static.suspend_sender, &task_high.sched_node);

    // Step 2: When - 脱离邮箱
    mrtk_err_t ret = mrtk_mb_detach(&test_mb_static);

    // Step 3: Then - 验证返回值和任务状态
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(task_high.last_error, MRTK_EDELETED);
}

/* ==============================================================================
 * mrtk_mb_create() 测试用例
 * ============================================================================== */

/**
 * @test MB_Create_ValidParameters_Success
 * @brief 测试正常创建动态邮箱
 * @details 验证动态创建的邮箱是否正确初始化
 * @Given 有效的邮箱容量和名称
 * @When 调用 mrtk_mb_create()
 * @Then 返回有效的邮箱指针，状态正确
 */
TEST_F(MrtkMailBoxTest, MB_Create_ValidParameters_Success) {
    // Step 1: Given - 有效的邮箱参数
    const mrtk_char_t *mb_name = "DynamicMB";
    mrtk_u32_t size = 128;

    // Step 2: When - 创建动态邮箱
    test_mb_dynamic = mrtk_mb_create(size, (mrtk_char_t *)mb_name, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 验证返回指针和状态
    ASSERT_NE(test_mb_dynamic, nullptr);
    EXPECT_NE(test_mb_dynamic->msg_pool, nullptr);
    EXPECT_GT(test_mb_dynamic->max_mail_cnt, 0);
    verify_mb_state(test_mb_dynamic, 0, 0, 0);
}

/**
 * @test MB_Create_NullName_ReturnsNull
 * @brief 测试 MRTK_NULL 名称参数（防御性测试）
 * @Given MRTK_NULL 名称参数
 * @When 调用 mrtk_mb_create()
 * @Then 返回 MRTK_NULL 或触发断言
 */
TEST_F(MrtkMailBoxTest, MB_Create_NullName_ReturnsNull) {
    // Step 1: Given - MRTK_NULL 名称参数
    // Step 2: When - 创建邮箱
    mrtk_mb_t *mb = mrtk_mb_create(128, nullptr, MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 3: Then - 预期返回 MRTK_NULL
    EXPECT_EQ(mb, nullptr);
}

/* ==============================================================================
 * mrtk_mb_delete() 测试用例
 * ============================================================================== */

/**
 * @test MB_Delete_ValidDynamicMB_Success
 * @brief 测试正常删除动态邮箱
 * @details 验证删除后邮箱内存被释放
 * @Given 动态创建的邮箱
 * @When 调用 mrtk_mb_delete()
 * @Then 返回 MRTK_EOK，内存被释放
 */
TEST_F(MrtkMailBoxTest, MB_Delete_ValidDynamicMB_Success) {
    // Step 1: Given - 创建动态邮箱
    test_mb_dynamic = mrtk_mb_create(128, "TestMB", MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    ASSERT_NE(test_mb_dynamic, nullptr);

    // Step 2: When - 删除邮箱
    mrtk_err_t ret = mrtk_mb_delete(test_mb_dynamic);

    // Step 3: Then - 验证返回值
    EXPECT_EQ(ret, MRTK_EOK);
    test_mb_dynamic = nullptr; /* 避免重复释放 */
}

/**
 * @test MB_Delete_WithWaitingSenders_SendersResumedWithError
 * @brief 测试删除时有等待发送者的邮箱
 * @details 验证删除时唤醒所有等待发送者
 * @Given 邮箱已满，有任务在等待发送队列中
 * @When 调用 mrtk_mb_delete()
 * @Then 所有等待发送者被唤醒，last_error 设置为 MRTK_EDELETED
 */
TEST_F(MrtkMailBoxTest, MB_Delete_WithWaitingSenders_SendersResumedWithError) {
    // Step 1: Given - 创建邮箱并填满，有任务等待发送
    test_mb_dynamic = mrtk_mb_create(sizeof(mrtk_u32_t), "TestMB",
                                      MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // 填满邮箱
    mrtk_u32_t mail = 0x12345678;
    mrtk_mb_send_wait(test_mb_dynamic, &mail, 0);

    // 将高优先级任务挂起到发送者等待队列
    set_current_task(&task_high);
    make_task_suspend(&task_high);
    task_high.last_error = MRTK_EOK;
    _mrtk_list_insert_before(&test_mb_dynamic->suspend_sender, &task_high.sched_node);

    // Step 2: When - 删除邮箱
    mrtk_err_t ret = mrtk_mb_delete(test_mb_dynamic);

    // Step 3: Then - 验证返回值和任务状态
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(task_high.last_error, MRTK_EDELETED);
    test_mb_dynamic = nullptr;
}

/* ==============================================================================
 * mrtk_mb_send_wait() 测试用例
 * ============================================================================== */

/**
 * @test MB_Send_EmptyMailbox_Success
 * @brief 测试向空邮箱发送邮件
 * @details 验证邮箱未满时能成功发送
 * @Given 空邮箱和有效的邮件
 * @When 调用 mrtk_mb_send_wait()
 * @Then 返回 MRTK_EOK，邮件被写入，cur_mail_cnt 加 1
 */
TEST_F(MrtkMailBoxTest, MB_Send_EmptyMailbox_Success) {
    // Step 1: Given - 初始化空邮箱
    mrtk_mb_init(&test_mb_static, mb_pool_buffer, MAILBOX_SIZE, "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_u32_t mail = 0xDEADBEEF;

    // Step 2: When - 发送邮件
    mrtk_err_t ret = mrtk_mb_send_wait(&test_mb_static, &mail, 100);

    // Step 3: Then - 验证成功发送
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mb_static.cur_mail_cnt, 1);
}

/**
 * @test MB_FullToEmptyToFull_VerifyOffsetsCycle
 * @brief 测试邮箱满→空→满循环过程中的偏移量循环切换
 * @details 验证 in_offset 在 0/1 之间循环切换，模拟环形缓冲区特性
 * @Given 邮箱容量为 2
 * @When 填满邮箱→排空邮箱→再次填满
 * @Then in_offset 正确循环切换，邮箱可循环使用
 */
TEST_F(MrtkMailBoxTest, MB_FullToEmptyToFull_VerifyOffsetsCycle) {
    // Step 1: Given - 初始化邮箱（容量为 2）
    mrtk_u32_t small_pool[2];
    mrtk_mb_init(&test_mb_static, small_pool, sizeof(small_pool), "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 第一次填满邮箱（验证 in_offset 循环：0→1→0）
    mrtk_u32_t mail1 = 0x11111111;
    mrtk_mb_send_wait(&test_mb_static, &mail1, 0);
    ASSERT_EQ(test_mb_static.in_offset, 1);  /* 验证 in_offset: 0→1 */
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 1);

    mrtk_u32_t mail2 = 0x22222222;
    mrtk_mb_send_wait(&test_mb_static, &mail2, 0);
    ASSERT_EQ(test_mb_static.in_offset, 0);  /* 验证 in_offset: 1→0 (循环回到起点) */
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 2);  /* 邮箱已满 */

    // Step 3: Then - 排空邮箱并再次填满（验证可循环使用）
    mrtk_u32_t recv_mail;
    mrtk_mb_recv(&test_mb_static, &recv_mail, 0);
    ASSERT_EQ(recv_mail, mail1);  /* FIFO 顺序 */
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 1);

    mrtk_mb_recv(&test_mb_static, &recv_mail, 0);
    ASSERT_EQ(recv_mail, mail2);
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 0);  /* 邮箱已空 */

    // 再次填满邮箱（验证 in_offset 再次循环：0→1→0）
    mrtk_u32_t mail3 = 0x33333333;
    mrtk_mb_send_wait(&test_mb_static, &mail3, 0);
    ASSERT_EQ(test_mb_static.in_offset, 1);  /* 验证 in_offset: 0→1 */
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 1);

    mrtk_u32_t mail4 = 0x44444444;
    mrtk_mb_send_wait(&test_mb_static, &mail4, 0);
    ASSERT_EQ(test_mb_static.in_offset, 0);  /* 验证 in_offset: 1→0 (再次循环) */
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 2);  /* 邮箱再次满 */
}

/**
 * @test MB_Send_FullMailbox_ZeroTimeout_ImmediateFailure
 * @brief 测试向满邮箱发送（非阻塞）
 * @details 验证邮箱满且 timeout=0 时立即返回错误
 * @Given 满邮箱
 * @When 以 timeout=0 调用 mrtk_mb_send_wait()
 * @Then 返回 MRTK_ERROR
 */
TEST_F(MrtkMailBoxTest, MB_Send_FullMailbox_ZeroTimeout_ImmediateFailure) {
    // Step 1: Given - 初始化邮箱并填满
    mrtk_mb_init(&test_mb_static, mb_pool_small, sizeof(mrtk_u32_t), "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_u32_t mail = 0x12345678;
    mrtk_mb_send_wait(&test_mb_static, &mail, 0);
    ASSERT_EQ(test_mb_static.cur_mail_cnt, test_mb_static.max_mail_cnt);

    // Step 2: When - 尝试非阻塞发送
    mrtk_err_t ret = mrtk_mb_send_wait(&test_mb_static, &mail, 0);

    // Step 3: Then - 验证立即返回错误
    EXPECT_EQ(ret, MRTK_EFULL);
}

/**
 * @test MB_Send_NullMail_ReturnsError
 * @brief 测试 MRTK_NULL 邮件指针（防御性测试）
 * @Given MRTK_NULL 邮件指针
 * @When 调用 mrtk_mb_send_wait()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMailBoxTest, MB_Send_NullMail_ReturnsError) {
    // Step 1: Given - 初始化邮箱
    mrtk_mb_init(&test_mb_static, mb_pool_buffer, MAILBOX_SIZE, "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);

    // Step 2: When - 发送 MRTK_NULL 邮件指针（非阻塞模式，避免永久阻塞）
    mrtk_err_t ret = mrtk_mb_send_wait(&test_mb_static, nullptr, 0);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test MB_Send_NullMB_ReturnsError
 * @brief 测试 MRTK_NULL 邮箱指针（防御性测试）
 * @Given MRTK_NULL 邮箱指针
 * @When 调用 mrtk_mb_send_wait()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMailBoxTest, MB_Send_NullMB_ReturnsError) {
    // Step 1: Given - MRTK_NULL 邮箱指针
    mrtk_u32_t mail = 0x12345678;
    set_current_task(&task_high);

    // Step 2: When - 发送到 MRTK_NULL 邮箱（非阻塞模式，避免永久阻塞）
    mrtk_err_t ret = mrtk_mb_send_wait(nullptr, &mail, 0);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_mb_recv() 测试用例
 * ============================================================================== */

/**
 * @test MB_Recv_NonEmptyMailbox_Success
 * @brief 测试从非空邮箱接收邮件
 * @details 验证邮箱有邮件时能成功接收
 * @Given 有邮件的邮箱
 * @When 调用 mrtk_mb_recv()
 * @Then 返回 MRTK_EOK，接收正确邮件，cur_mail_cnt 减 1
 */
TEST_F(MrtkMailBoxTest, MB_Recv_NonEmptyMailbox_Success) {
    // Step 1: Given - 初始化邮箱并发送 1 封邮件
    mrtk_mb_init(&test_mb_static, mb_pool_buffer, MAILBOX_SIZE, "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_u32_t sent_mail = 0xABCDEF00;
    mrtk_mb_send_wait(&test_mb_static, &sent_mail, 0);
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 1);

    // Step 2: When - 接收邮件
    mrtk_u32_t recv_mail;
    mrtk_err_t ret = mrtk_mb_recv(&test_mb_static, &recv_mail, 100);

    // Step 3: Then - 验证成功接收
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(recv_mail, sent_mail);
    EXPECT_EQ(test_mb_static.cur_mail_cnt, 0);
}

/**
 * @test MB_Recv_EmptyMailbox_ZeroTimeout_ImmediateFailure
 * @brief 测试从空邮箱接收（非阻塞）
 * @details 验证邮箱空且 timeout=0 时立即返回错误
 * @Given 空邮箱
 * @When 以 timeout=0 调用 mrtk_mb_recv()
 * @Then 返回 MRTK_ERROR
 */
TEST_F(MrtkMailBoxTest, MB_Recv_EmptyMailbox_ZeroTimeout_ImmediateFailure) {
    // Step 1: Given - 初始化空邮箱
    mrtk_mb_init(&test_mb_static, mb_pool_buffer, MAILBOX_SIZE, "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 尝试非阻塞接收
    mrtk_u32_t recv_mail;
    mrtk_err_t ret = mrtk_mb_recv(&test_mb_static, &recv_mail, 0);

    // Step 3: Then - 验证立即返回错误
    EXPECT_EQ(ret, MRTK_EEMPTY);
}

/**
 * @test MB_RoundTrip_FillAndDrain_VerifyOffsets
 * @brief 测试环形缓冲区填满和排空过程中的偏移量变化
 * @details 验证 in_offset 和 out_offset 在 0/1 之间正确切换（模拟环形特性）
 * @Given 邮箱容量为 2
 * @When 填满邮箱→排空邮箱→再次发送接收
 * @Then 偏移量正确切换，数据 FIFO 顺序正确
 */
TEST_F(MrtkMailBoxTest, MB_RoundTrip_FillAndDrain_VerifyOffsets) {
    // Step 1: Given - 初始化邮箱（容量为 2）
    mrtk_u32_t small_pool[2];
    mrtk_mb_init(&test_mb_static, small_pool, sizeof(small_pool), "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 填满邮箱（验证 in_offset 在 0/1 间切换）
    mrtk_u32_t mail1 = 0x11111111;
    mrtk_u32_t mail2 = 0x22222222;
    mrtk_mb_send_wait(&test_mb_static, &mail1, 0);
    ASSERT_EQ(test_mb_static.in_offset, 1);  /* 验证 in_offset: 0→1 */
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 1);

    mrtk_mb_send_wait(&test_mb_static, &mail2, 0);
    ASSERT_EQ(test_mb_static.in_offset, 0);  /* 验证 in_offset: 1→0 (模拟回绕) */
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 2);  /* 邮箱已满 */

    // Step 3: Then - 排空邮箱（验证 out_offset 在 0/1 间切换，数据 FIFO 顺序）
    mrtk_u32_t recv_mail;
    mrtk_mb_recv(&test_mb_static, &recv_mail, 0);
    ASSERT_EQ(recv_mail, mail1);  /* FIFO: 先进先出 */
    ASSERT_EQ(test_mb_static.out_offset, 1);  /* 验证 out_offset: 0→1 */
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 1);

    mrtk_mb_recv(&test_mb_static, &recv_mail, 0);
    ASSERT_EQ(recv_mail, mail2);  /* FIFO: 后进后出 */
    ASSERT_EQ(test_mb_static.out_offset, 0);  /* 验证 out_offset: 1→0 (模拟回绕) */
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 0);  /* 邮箱已空 */

    // Step 4: When - 再次发送和接收（验证邮箱可重复使用）
    mrtk_u32_t mail3 = 0x33333333;
    mrtk_mb_send_wait(&test_mb_static, &mail3, 0);
    ASSERT_EQ(test_mb_static.in_offset, 1);  /* 验证 in_offset: 0→1 */
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 1);

    mrtk_mb_recv(&test_mb_static, &recv_mail, 0);
    ASSERT_EQ(recv_mail, mail3);
    ASSERT_EQ(test_mb_static.out_offset, 1);  /* 验证 out_offset: 0→1 */
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 0);
}

/**
 * @test MB_Recv_NullMail_ReturnsError
 * @brief 测试 MRTK_NULL 邮件缓冲区指针（防御性测试）
 * @Given MRTK_NULL 邮件缓冲区指针
 * @When 调用 mrtk_mb_recv()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMailBoxTest, MB_Recv_NullMail_ReturnsError) {
    // Step 1: Given - 初始化邮箱
    mrtk_mb_init(&test_mb_static, mb_pool_buffer, MAILBOX_SIZE, "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);

    // Step 2: When - 接收到 MRTK_NULL 缓冲区（非阻塞模式，避免永久阻塞）
    mrtk_err_t ret = mrtk_mb_recv(&test_mb_static, nullptr, 0);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/**
 * @test MB_Recv_NullMB_ReturnsError
 * @brief 测试 MRTK_NULL 邮箱指针（防御性测试）
 * @Given MRTK_NULL 邮箱指针
 * @When 调用 mrtk_mb_recv()
 * @Then 触发 MRTK_ASSERT
 */
TEST_F(MrtkMailBoxTest, MB_Recv_NullMB_ReturnsError) {
    // Step 1: Given - MRTK_NULL 邮箱指针
    mrtk_u32_t recv_mail;
    set_current_task(&task_high);

    // Step 2: When - 从 MRTK_NULL 邮箱接收（非阻塞模式，避免永久阻塞）
    mrtk_err_t ret = mrtk_mb_recv(nullptr, &recv_mail, 0);

    // Step 3: Then - 预期返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * mrtk_mb_control() 测试用例
 * ============================================================================== */

/**
 * @test MB_Control_ResetCmd_EmptiesMailbox
 * @brief 测试重置命令
 * @details 验证 RESET 命令清空邮箱并唤醒所有等待任务
 * @Given 有邮件和等待任务的邮箱
 * @When 使用 MRTK_MB_CMD_RESET 命令
 * @Then 邮箱被清空，所有等待任务被唤醒
 */
TEST_F(MrtkMailBoxTest, MB_Control_ResetCmd_EmptiesMailbox) {
    // Step 1: Given - 初始化邮箱并发送邮件
    /* 注意：必须使用 sizeof(mb_pool_small) 而不是 sizeof(mrtk_u32_t)，
     * 否则对齐后容量为 0，导致无法发送邮件 */
    mrtk_mb_init(&test_mb_static, mb_pool_small, sizeof(mb_pool_small), "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_u32_t mail = 0x12345678;
    mrtk_err_t ret_send = mrtk_mb_send_wait(&test_mb_static, &mail, 0);
    ASSERT_EQ(ret_send, MRTK_EOK);
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 1);

    // Step 2: When - 使用 RESET 命令（注意：代码中使用的是 MRTK_MB_CMD_RESET）
    mrtk_err_t ret = mrtk_mb_control(&test_mb_static, MRTK_MB_CMD_RESET, nullptr);

    // Step 3: Then - 验证邮箱被清空
    EXPECT_EQ(ret, MRTK_EOK);
    EXPECT_EQ(test_mb_static.cur_mail_cnt, 0);
    EXPECT_EQ(test_mb_static.in_offset, 0);
    EXPECT_EQ(test_mb_static.out_offset, 0);
}

/**
 * @test MB_Control_InvalidCmd_ReturnsError
 * @brief 测试无效的控制命令（防御性测试）
 * @Given 有效的邮箱
 * @When 使用无效命令
 * @Then 返回 MRTK_ERROR
 */
TEST_F(MrtkMailBoxTest, MB_Control_InvalidCmd_ReturnsError) {
    // Step 1: Given - 初始化邮箱
    mrtk_mb_init(&test_mb_static, mb_pool_buffer, MAILBOX_SIZE, "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 使用无效命令
    mrtk_err_t ret = mrtk_mb_control(&test_mb_static, 0xFFFF, nullptr);

    // Step 3: Then - 验证返回错误
    EXPECT_EQ(ret, MRTK_EINVAL);
}

/* ==============================================================================
 * 综合场景测试
 * ============================================================================== */

/**
 * @test MB_CompleteLifecycle_InitSendRecvDetach_Success
 * @brief 测试邮箱完整生命周期
 * @details 验证 Init → Send → Recv → Detach 的完整流程
 * @Given 邮箱对象
 * @When 依次执行 init, send, recv, detach
 * @Then 每一步都成功返回
 */
TEST_F(MrtkMailBoxTest, MB_CompleteLifecycle_InitSendRecvDetach_Success) {
    // Step 1: Given - 邮箱对象和任务

    // Step 2: When - 执行完整生命周期
    mrtk_err_t ret_init = mrtk_mb_init(&test_mb_static, mb_pool_buffer, MAILBOX_SIZE, "LifecycleMB",
                                         MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    set_current_task(&task_high);
    make_task_ready(&task_high);

    mrtk_u32_t sent_mail = 0x99887766;
    mrtk_err_t ret_send = mrtk_mb_send_wait(&test_mb_static, &sent_mail, 100);

    mrtk_u32_t recv_mail;
    mrtk_err_t ret_recv = mrtk_mb_recv(&test_mb_static, &recv_mail, 100);

    mrtk_err_t ret_detach = mrtk_mb_detach(&test_mb_static);

    // Step 3: Then - 验证每一步都成功
    EXPECT_EQ(ret_init, MRTK_EOK);
    EXPECT_EQ(ret_send, MRTK_EOK);
    EXPECT_EQ(ret_recv, MRTK_EOK);
    EXPECT_EQ(recv_mail, sent_mail);
    EXPECT_EQ(ret_detach, MRTK_EOK);
}

/**
 * @test MB_ProducerConsumer_MultipleTasks
 * @brief 测试生产者-消费者模式
 * @details 验证多任务发送和接收的正确性
 * @Given 多个任务向同一邮箱发送和接收邮件
 * @When 各任务进行 send/recv 操作
 * @Then 邮件正确传递，无数据损坏
 */
TEST_F(MrtkMailBoxTest, MB_ProducerConsumer_MultipleTasks) {
    // Step 1: Given - 初始化邮箱
    mrtk_u32_t pool[8]; /* 容量为 8 */
    mrtk_mb_init(&test_mb_static, pool, sizeof(pool), "PCMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    // Step 2: When - 高优先级任务发送 3 封邮件
    set_current_task(&task_high);
    make_task_ready(&task_high);

    for (mrtk_u32_t i = 0; i < 3; ++i) {
        mrtk_u32_t mail = 0x10000000 | i;
        mrtk_err_t ret = mrtk_mb_send_wait(&test_mb_static, &mail, 0);
        ASSERT_EQ(ret, MRTK_EOK);
    }

    // Step 3: Then - 中优先级任务接收 3 封邮件并验证
    set_current_task(&task_mid);
    make_task_ready(&task_mid);

    for (mrtk_u32_t i = 0; i < 3; ++i) {
        mrtk_u32_t recv_mail;
        mrtk_err_t ret = mrtk_mb_recv(&test_mb_static, &recv_mail, 0);
        EXPECT_EQ(ret, MRTK_EOK);
        EXPECT_EQ(recv_mail, (0x10000000 | i));
    }

    EXPECT_EQ(test_mb_static.cur_mail_cnt, 0);
}

/**
 * @test MB_FullMailbox_WakeupSenderOnRecv
 * @brief 测试邮箱满时发送者阻塞，接收后唤醒发送者
 * @details 验证双向唤醒机制
 * @Given 邮箱已满，有任务等待发送
 * @When 接收邮件腾出空间
 * @Then 等待的发送者被唤醒
 */
TEST_F(MrtkMailBoxTest, MB_FullMailbox_WakeupSenderOnRecv) {
    // Step 1: Given - 初始化邮箱（容量为 1）并填满
    mrtk_u32_t small_pool[1];
    mrtk_mb_init(&test_mb_static, small_pool, sizeof(small_pool), "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);

    set_current_task(&task_high);
    make_task_ready(&task_high);
    mrtk_u32_t mail1 = 0x11111111;
    mrtk_mb_send_wait(&test_mb_static, &mail1, 0);
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 1);

    // Step 2: When - 接收邮件腾出空间
    mrtk_u32_t recv_mail;
    mrtk_err_t ret_recv = mrtk_mb_recv(&test_mb_static, &recv_mail, 0);

    // Step 3: Then - 验证邮箱变为空
    EXPECT_EQ(ret_recv, MRTK_EOK);
    EXPECT_EQ(recv_mail, mail1);
    EXPECT_EQ(test_mb_static.cur_mail_cnt, 0);
}

/**
 * @test MB_RoundTrip_CompleteCycle
 * @brief 测试完整的发送-接收循环
 * @details 验证环形缓冲区的完整读写循环
 * @Given 邮箱容量为 N
 * @When 发送 N 封邮件，然后接收 N 封邮件
 * @Then 偏移量正确回绕，数据完整
 */
TEST_F(MrtkMailBoxTest, MB_RoundTrip_CompleteCycle) {
    // Step 1: Given - 初始化邮箱（容量为 4）
    mrtk_u32_t pool[4];
    mrtk_mb_init(&test_mb_static, pool, sizeof(pool), "TestMB",
                 MRTK_IPC_FLAG_NOTIFY_POLICY_PRIO);
    set_current_task(&task_high);
    make_task_ready(&task_high);

    // Step 2: When - 发送 4 封邮件填满邮箱
    for (mrtk_u32_t i = 0; i < 4; ++i) {
        mrtk_u32_t mail = 0xAABBCC00 | i;
        mrtk_err_t ret = mrtk_mb_send_wait(&test_mb_static, &mail, 0);
        ASSERT_EQ(ret, MRTK_EOK);
    }
    ASSERT_EQ(test_mb_static.cur_mail_cnt, 4);
    ASSERT_EQ(test_mb_static.in_offset, 0); /* 回绕到 0 */

    // Step 3: Then - 接收 4 封邮件并验证数据完整性
    for (mrtk_u32_t i = 0; i < 4; ++i) {
        mrtk_u32_t recv_mail;
        mrtk_err_t ret = mrtk_mb_recv(&test_mb_static, &recv_mail, 0);
        EXPECT_EQ(ret, MRTK_EOK);
        EXPECT_EQ(recv_mail, (0xAABBCC00 | i));
    }

    EXPECT_EQ(test_mb_static.cur_mail_cnt, 0);
    EXPECT_EQ(test_mb_static.out_offset, 0); /* 回绕到 0 */
}

#endif /* (MRTK_USING_MAILBOX == 1) */
